# Generated by Django 5.2.12 on 2026-05-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synthetic", "0003_syntheticopportunity_allowed_domains_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabsLocalRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("experiment", models.CharField(db_index=True, max_length=200)),
                ("type", models.CharField(db_index=True, max_length=100)),
                ("data", models.JSONField(default=dict)),
                ("public", models.BooleanField(default=False)),
                ("opportunity_id", models.IntegerField(db_index=True)),
                ("organization_id", models.IntegerField(blank=True, null=True)),
                ("program_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("labs_record_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("username", models.CharField(blank=True, default="", max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Labs-local LabsRecord",
                "verbose_name_plural": "Labs-local LabsRecords",
                "db_table": "labs_local_labs_record",
                "ordering": ["-id"],
            },
        ),
    ]
