# Generated by Django 5.2.12 on 2026-06-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synthetic", "0006_syntheticopportunity_visit_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="syntheticopportunity",
            name="cloned_from_opportunity_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="The real Connect opportunity_id this labs-only opp was cloned from (provenance + clone idempotency). Null for opps not produced by the clone pipeline.",
                null=True,
            ),
        ),
    ]
