# Generated by Django 6.0.8 on 2026-09-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synthetic", "0008_labslocalrecord_opportunity_id_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="syntheticopportunity",
            name="generated_folder_id",
            field=models.CharField(
                blank=True,
                help_text="The fixture folder the synthetic GENERATOR wrote for this opp. The opp's data is generated (never real) only while gdrive_folder_id still equals this, so pointing the opp at any other folder un-marks it with no code path to remember. Null = not generated. Set only by server code: see connect_labs/labs/synthetic/provenance.py.",
                max_length=200,
                null=True,
            ),
        ),
    ]
