# Generated by Django 5.2.12 on 2026-05-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_boundaries", "0002_adminboundary_unique_source_boundary_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminboundary",
            name="extra",
            field=models.JSONField(blank=True, default=dict, help_text="Provider + denormalized hierarchy metadata"),
        ),
        migrations.AddField(
            model_name="adminboundary",
            name="parent_boundary_id",
            field=models.CharField(
                blank=True, db_index=True, help_text="boundary_id of the immediate parent unit", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="adminboundary",
            name="population",
            field=models.FloatField(blank=True, help_text="Population of the unit, if known", null=True),
        ),
        migrations.AlterField(
            model_name="adminboundary",
            name="boundary_id",
            field=models.CharField(help_text="ID from source (shapeID/OSM ID); unique per source", max_length=100),
        ),
        migrations.AlterField(
            model_name="adminboundary",
            name="source",
            field=models.CharField(
                choices=[
                    ("geoboundaries", "geoBoundaries"),
                    ("osm", "OpenStreetMap"),
                    ("grid3", "GRID3"),
                    ("hdx", "HDX (OCHA COD)"),
                    ("geopode", "GeoPoDe"),
                ],
                db_index=True,
                default="geoboundaries",
                help_text="Data source (geoBoundaries, OpenStreetMap, GRID3, or HDX)",
                max_length=20,
            ),
        ),
    ]
