# Generated by Django 5.2.12 on 2026-05-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_connectiduserlink_hq_case_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="view_synthetic_opps",
            field=models.BooleanField(
                default=False,
                help_text="When on, labs-only synthetic opportunities matching the user's email domain are merged into their labs_context org/program/opportunity lists.",
            ),
        ),
    ]
