# Generated by Django 5.2.12 on 2026-10-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_user_view_synthetic_opps"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mcp_no_uservisit_data",
            field=models.BooleanField(
                default=False,
                help_text="When on, every MCP call this person makes keeps to 'no user visit data' -- on either MCP address and with any token -- and the labs export API refuses them. For people who may use labs through Claude but must never see real visit data there.",
                verbose_name="MCP: no user visit data",
            ),
        ),
    ]
