/**
 * OES Supply (Operation End Starvation) — build step.
 *
 * Same shape as webpack/build-campaign.js, for the same reason: the files in
 * connect_labs/static/supply/ are NON-module scripts sharing one global scope
 * in a fixed load order (primitives.jsx defines Page/Card/DataTable/…;
 * app.jsx defines BOOTSTRAP and mounts the root). They use the GLOBAL
 * React/ReactDOM (classic JSX runtime), never import/export.
 *
 * We babel-transpile each file with the CLASSIC preset-react runtime and
 * concatenate in order — webpack is deliberately not used here, since its
 * per-module function scope would break the global-sharing contract.
 *
 * Output: connect_labs/static/bundles/js/supply-bundle.js
 */
const fs = require('fs');
const path = require('path');
const babel = require('@babel/core');

const SRC_DIR = path.resolve(__dirname, '../connect_labs/static/supply');
const OUT_DIR = path.resolve(__dirname, '../connect_labs/static/bundles/js');
const OUT_FILE = path.join(OUT_DIR, 'supply-bundle.js');

// EXACT load order. app.jsx MUST be last (it mounts the root).
const FILES = [
  'perms.js',
  'primitives.jsx',
  'data-api.js',
  'flowmap.jsx',
  'tab_supplier_home.jsx',
  'tab_org.jsx',
  'tab_eoi.jsx',
  'tab_bids.jsx',
  'tab_ops.jsx',
  'tab_integration.jsx',
  'tab_console_home.jsx',
  'tab_rounds.jsx',
  'tab_registry.jsx',
  'tab_rfps.jsx',
  'tab_command.jsx',
  'tab_gov.jsx',
  'tab_funder.jsx',
  'app.jsx',
];

function transpile(file) {
  const filename = path.join(SRC_DIR, file);
  const code = fs.readFileSync(filename, 'utf8');
  const result = babel.transformSync(code, {
    // Pin the CLASSIC react runtime: the repo default (runtime:"automatic")
    // would inject `import { jsx } from "react/jsx-runtime"` and break the
    // non-module global-scope contract.
    filename,
    babelrc: false,
    configFile: false,
    presets: [['@babel/preset-react', { runtime: 'classic' }]],
    compact: false,
    comments: false,
  });
  return result.code;
}

function build() {
  if (!fs.existsSync(OUT_DIR)) {
    fs.mkdirSync(OUT_DIR, { recursive: true });
  }

  const parts = [
    '/* OES Supply — built bundle. DO NOT EDIT.',
    ' * Generated by webpack/build-supply.js from static/supply/*.{jsx,js}.',
    ' * Concatenated in load order; runs in one shared global scope. */',
    '',
  ];

  for (const file of FILES) {
    parts.push(`/* ===== ${file} ===== */`);
    parts.push(transpile(file));
    parts.push('');
  }

  fs.writeFileSync(OUT_FILE, parts.join('\n'), 'utf8');
  const kb = (fs.statSync(OUT_FILE).size / 1024).toFixed(1);
  console.log(`[supply] built ${OUT_FILE} (${FILES.length} files, ${kb} KB)`);
}

build();

if (process.argv.includes('--watch')) {
  console.log('[supply] watching for changes…');
  let timer = null;
  const rebuild = () => {
    clearTimeout(timer);
    timer = setTimeout(() => {
      try {
        build();
      } catch (e) {
        console.error('[supply] build failed:', e.message);
      }
    }, 100);
  };
  for (const file of FILES) {
    fs.watch(path.join(SRC_DIR, file), rebuild);
  }
}
