# Generated by Django 6.0.8 on 2026-09-29 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowActionExecution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("via", models.CharField(max_length=16)),
                ("actor", models.CharField(blank=True, default="", max_length=100)),
                ("definition_id", models.IntegerField()),
                ("run_id", models.IntegerField(db_index=True)),
                ("opportunity_id", models.IntegerField(blank=True, null=True)),
                ("program_id", models.IntegerField(blank=True, null=True)),
                ("action_key", models.CharField(max_length=64)),
                ("action_type", models.CharField(max_length=64)),
                ("arguments", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("completed_with_errors", "Completed with errors"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("results", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["run_id", "action_key"], name="workflow_wo_run_id_231bbf_idx")],
            },
        ),
    ]
