# Generated by Django 6.0.8 on 2026-10-05 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_workflow_action_execution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateWorkflow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("workflow_id", models.IntegerField()),
                ("scope_key", models.CharField(max_length=40)),
                ("opportunity_id", models.IntegerField(blank=True, null=True)),
                ("program_id", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("template_scope", models.CharField(max_length=40)),
                ("template_type", models.CharField(blank=True, default="", max_length=100)),
                ("seeded_from", models.CharField(blank=True, default="", max_length=120)),
                ("draft_render_code", models.TextField(blank=True, default="")),
                ("draft_config", models.JSONField(blank=True, default=dict)),
                ("draft_snapshot_inputs", models.JSONField(blank=True, null=True)),
                ("draft_revision", models.IntegerField(default=1)),
                ("draft_updated_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draft_updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owners",
                    models.ManyToManyField(related_name="owned_template_workflows", to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateWorkflowVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.IntegerField()),
                ("render_code", models.TextField()),
                ("config", models.JSONField(blank=True, default=dict)),
                ("snapshot_inputs", models.JSONField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("restores_version", models.IntegerField(blank=True, null=True)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="workflow.templateworkflow",
                    ),
                ),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.AddField(
            model_name="templateworkflow",
            name="published",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="workflow.templateworkflowversion",
            ),
        ),
        migrations.CreateModel(
            name="TemplateWorkflowFollower",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("workflow_id", models.IntegerField()),
                ("scope_key", models.CharField(max_length=40)),
                ("opportunity_id", models.IntegerField(blank=True, null=True)),
                ("program_id", models.IntegerField(blank=True, null=True)),
                ("followed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "followed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="workflow.templateworkflow",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("template", "workflow_id", "scope_key"), name="uniq_template_follower"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="templateworkflowversion",
            constraint=models.UniqueConstraint(fields=("template", "number"), name="uniq_template_version"),
        ),
        migrations.AddConstraint(
            model_name="templateworkflow",
            constraint=models.UniqueConstraint(fields=("workflow_id", "scope_key"), name="uniq_template_workflow"),
        ),
    ]
