# Generated by Django 6.0.8 on 2026-10-05 22:45

from django.db import migrations


# connect-labs#2236: template workflows moved to LabsRecords under the LabsRecord ACL
# (workflow/template_workflows.py). Their one live template (25528, opp 523) was
# recreated there with workflow_template_import_legacy before this ran, so these
# tables hold nothing that is read any more.


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0002_template_workflows"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="templateworkflow",
            name="uniq_template_workflow",
        ),
        migrations.RemoveConstraint(
            model_name="templateworkflowfollower",
            name="uniq_template_follower",
        ),
        migrations.RemoveConstraint(
            model_name="templateworkflowversion",
            name="uniq_template_version",
        ),
        migrations.RemoveField(
            model_name="templateworkflow",
            name="draft_updated_by",
        ),
        migrations.RemoveField(
            model_name="templateworkflow",
            name="owners",
        ),
        migrations.RemoveField(
            model_name="templateworkflow",
            name="published",
        ),
        migrations.RemoveField(
            model_name="templateworkflowversion",
            name="published_by",
        ),
        migrations.RemoveField(
            model_name="templateworkflowversion",
            name="template",
        ),
        migrations.DeleteModel(
            name="TemplateWorkflowFollower",
        ),
        migrations.DeleteModel(
            name="TemplateWorkflow",
        ),
        migrations.DeleteModel(
            name="TemplateWorkflowVersion",
        ),
    ]
