"""End-to-end Postgres tests for WindowFieldComputation.

Verifies the SQL generated by build_visit_extraction_query when window_fields
are declared actually executes on real PostGIS and produces the right
distances. The single supported operation is `lag_haversine`, which calls
the haversine_meters function (migration 0012) inside a LAG() window.

This is the foundation that v3's GPS dashboard tab will sit on. With this
PR, declaring a `WindowFieldComputation(operation="lag_haversine", ...)` in
a pipeline schema produces a `distance_from_prev_case_visit_m`-style column
in the visit-level extraction output. Downstream aggregations (median,
sum, count > 5000, etc.) then work without modification.
"""

import pytest
from django.db import connection
from django.utils import timezone

from commcare_connect.labs.analysis.backends.sql.models import RawVisitCache
from commcare_connect.labs.analysis.backends.sql.query_builder import build_visit_extraction_query
from commcare_connect.labs.analysis.config import (
    AnalysisPipelineConfig,
    CacheStage,
    FieldComputation,
    WindowFieldComputation,
)


@pytest.mark.django_db
class TestLagHaversineWindow:
    """Pipeline-level integration of lag_haversine window field."""

    def _seed(self, opp_id: int, rows: list[tuple]) -> None:
        """Seed labs_raw_visit_cache. rows is list of
        (visit_id, mother_case_id, lat, lon, datetime_iso).

        Stores lat/lon as separate JSON fields (form.lat / form.lon) rather
        than as a packed "lat lon altitude accuracy" string, so the test
        doesn't depend on the transform-system's lambda-source detection
        (which doesn't recognise split-and-index lambdas and falls back to
        passthrough). Production MBW data has GPS as the packed string;
        wiring that into the window-field path is orthogonal to this test
        and tracked separately.
        """
        future = timezone.now() + timezone.timedelta(days=1)
        for i, (vid, mid, lat, lon, dt) in enumerate(rows):
            RawVisitCache.objects.create(
                opportunity_id=opp_id,
                visit_count=len(rows),
                expires_at=future,
                visit_id=str(vid),
                username="flw_a",
                form_json={
                    "form": {
                        "parents": {"parent": {"case": {"@case_id": mid}}},
                        "meta": {"timeEnd": dt},
                        "lat": str(lat),
                        "lon": str(lon),
                    }
                },
                visit_date=dt[:10],
                status="approved",
            )

    def _config_with_lag_haversine(self) -> AnalysisPipelineConfig:
        return AnalysisPipelineConfig(
            grouping_key="username",
            terminal_stage=CacheStage.VISIT_LEVEL,
            fields=[
                FieldComputation(name="latitude", path="form.lat", aggregation="first"),
                FieldComputation(name="longitude", path="form.lon", aggregation="first"),
                FieldComputation(
                    name="mother_case_id",
                    path="form.parents.parent.case.@case_id",
                    aggregation="first",
                ),
                FieldComputation(name="visit_datetime", path="form.meta.timeEnd", aggregation="first"),
            ],
            window_fields=[
                WindowFieldComputation(
                    name="distance_from_prev_case_visit_m",
                    operation="lag_haversine",
                    partition_by="mother_case_id",
                    order_by="visit_datetime",
                    lat_field="latitude",
                    lon_field="longitude",
                ),
            ],
        )

    def test_first_visit_in_partition_yields_null_distance(self, db):
        """The first visit to each mother has no previous, so LAG returns
        NULL → haversine_meters returns NULL."""
        self._seed(
            10001,
            [
                (1, "m1", -1.0000, 35.0000, "2024-01-10T09:00:00"),
                (2, "m1", -1.0010, 35.0000, "2024-01-10T10:00:00"),
                (3, "m2", -2.0000, 36.0000, "2024-01-10T11:00:00"),
            ],
        )
        config = self._config_with_lag_haversine()
        query, _ = build_visit_extraction_query(config, opportunity_id=10001)

        with connection.cursor() as cur:
            cur.execute(query)
            cols = [c[0] for c in cur.description]
            rows = [dict(zip(cols, r)) for r in cur.fetchall()]

        # Row 1 (mother m1, first visit) → distance is NULL
        # Row 2 (mother m1, second visit) → distance ~111m to row 1
        # Row 3 (mother m2, first visit) → distance is NULL
        rows_by_visit = {r["visit_id"]: r for r in rows}
        assert rows_by_visit["1"]["distance_from_prev_case_visit_m"] is None
        assert rows_by_visit["2"]["distance_from_prev_case_visit_m"] == pytest.approx(111, abs=2)
        assert rows_by_visit["3"]["distance_from_prev_case_visit_m"] is None

    def test_partitions_independent(self, db):
        """LAG within mother A's partition doesn't see mother B's rows."""
        self._seed(
            10002,
            [
                # Same mother, two visits 100km apart → row 2 distance = 100km
                (1, "ma", -1.0000, 35.0000, "2024-01-10T09:00:00"),
                (2, "ma", -1.0000, 35.9000, "2024-01-10T11:00:00"),
                # Different mother in between, very close to ma's location —
                # if the partition were cross-mother, row 2's distance would
                # be tiny. With per-mother partitioning, it stays 100km.
                (3, "mb", -1.0001, 35.0001, "2024-01-10T10:00:00"),
            ],
        )
        config = self._config_with_lag_haversine()
        query, _ = build_visit_extraction_query(config, opportunity_id=10002)

        with connection.cursor() as cur:
            cur.execute(query)
            cols = [c[0] for c in cur.description]
            rows = [dict(zip(cols, r)) for r in cur.fetchall()]

        rows_by_visit = {r["visit_id"]: r for r in rows}
        # mother ma: 1° longitude apart at the equator ≈ 100 km
        assert rows_by_visit["2"]["distance_from_prev_case_visit_m"] == pytest.approx(100_000, abs=200)
        # mother mb single-visit
        assert rows_by_visit["3"]["distance_from_prev_case_visit_m"] is None

    def test_order_within_partition_uses_visit_datetime(self, db):
        """When visits are inserted out of chronological order, LAG must
        still order by visit_datetime — so distance is between THE
        previous visit BY DATETIME, not the previous row inserted.
        """
        # Insert in non-chrono order; window's ORDER BY visit_datetime
        # should fix the sequence.
        self._seed(
            10003,
            [
                (1, "m1", -1.0000, 35.0000, "2024-01-10T09:00:00"),  # earliest
                (3, "m1", -1.0020, 35.0000, "2024-01-10T11:00:00"),  # latest, third
                (2, "m1", -1.0010, 35.0000, "2024-01-10T10:00:00"),  # middle, second
            ],
        )
        config = self._config_with_lag_haversine()
        query, _ = build_visit_extraction_query(config, opportunity_id=10003)

        with connection.cursor() as cur:
            cur.execute(query)
            cols = [c[0] for c in cur.description]
            rows = [dict(zip(cols, r)) for r in cur.fetchall()]

        rows_by_visit = {r["visit_id"]: r for r in rows}
        # By visit_datetime: 1 → 2 → 3.
        # Row 1 first → NULL.
        # Row 2 (10:00) prev = row 1 (09:00) → ~111m.
        # Row 3 (11:00) prev = row 2 (10:00) → ~111m.
        assert rows_by_visit["1"]["distance_from_prev_case_visit_m"] is None
        assert rows_by_visit["2"]["distance_from_prev_case_visit_m"] == pytest.approx(111, abs=2)
        assert rows_by_visit["3"]["distance_from_prev_case_visit_m"] == pytest.approx(111, abs=2)

    def test_no_window_fields_keeps_flat_query(self, db):
        """Backwards compatibility: a config with no window_fields produces
        the SAME query shape as before — no subquery wrapper, no window
        functions in the SELECT list."""
        config = AnalysisPipelineConfig(
            grouping_key="username",
            terminal_stage=CacheStage.VISIT_LEVEL,
            fields=[
                FieldComputation(name="some_field", path="form.x", aggregation="first"),
            ],
        )
        query, fields = build_visit_extraction_query(config, opportunity_id=99999)
        # No window-shape markers in the emitted SQL
        assert "PARTITION BY" not in query
        assert "LAG(" not in query
        assert "haversine_meters(" not in query
        assert fields == ["some_field"]


@pytest.mark.django_db
class TestGpsTransformsExecuteEndToEnd:
    """gps_lat / gps_lon transforms must produce correct floats from packed
    'lat lon altitude accuracy' GPS strings, when run through the full
    extraction pipeline (build_visit_extraction_query + Postgres).
    """

    def _seed_packed_gps(self, opp_id: int, rows: list[tuple]) -> None:
        future = timezone.now() + timezone.timedelta(days=1)
        for i, (vid, mid, gps_str, dt) in enumerate(rows):
            RawVisitCache.objects.create(
                opportunity_id=opp_id,
                visit_count=len(rows),
                expires_at=future,
                visit_id=str(vid),
                username="flw_a",
                form_json={
                    "form": {
                        "parents": {"parent": {"case": {"@case_id": mid}}},
                        "meta": {"timeEnd": dt, "location": gps_str},
                    }
                },
                visit_date=dt[:10],
                status="approved",
            )

    def test_gps_transforms_extract_lat_lon_then_lag_haversine(self, db):
        """End-to-end: a config declaring gps_lat/gps_lon transforms PLUS a
        lag_haversine window field over those transforms produces the right
        per-visit distance. This is the path v3's `visits_gps` pipeline takes.
        """
        from commcare_connect.workflow.data_access import PipelineDataAccess

        # Seed three visits to the same mother, GPS in packed form.
        self._seed_packed_gps(
            20001,
            [
                (1, "m1", "-1.0000 35.0000 1000 10", "2024-01-10T09:00:00"),
                (2, "m1", "-1.0010 35.0000 1000 10", "2024-01-10T10:00:00"),
                (3, "m1", "-1.0020 35.0000 1000 10", "2024-01-10T11:00:00"),
            ],
        )

        schema = {
            "data_source": {"type": "connect_csv"},
            "grouping_key": "username",
            "terminal_stage": "visit_level",
            "fields": [
                {"name": "mother_case_id", "path": "form.parents.parent.case.@case_id", "aggregation": "first"},
                {"name": "visit_datetime", "path": "form.meta.timeEnd", "aggregation": "first"},
                {"name": "latitude", "path": "form.meta.location", "aggregation": "first", "transform": "gps_lat"},
                {"name": "longitude", "path": "form.meta.location", "aggregation": "first", "transform": "gps_lon"},
            ],
            "window_fields": [
                {
                    "name": "distance_from_prev_case_visit_m",
                    "operation": "lag_haversine",
                    "partition_by": "mother_case_id",
                    "order_by": "visit_datetime",
                    "lat_field": "latitude",
                    "lon_field": "longitude",
                },
            ],
        }
        access = type("_Fake", (PipelineDataAccess,), {"__init__": lambda self: None})()
        config = access._schema_to_config(schema, definition_id=20001)

        from commcare_connect.labs.analysis.backends.sql.query_builder import build_visit_extraction_query

        query, _ = build_visit_extraction_query(config, opportunity_id=20001)

        with connection.cursor() as cur:
            cur.execute(query)
            cols = [c[0] for c in cur.description]
            rows = [dict(zip(cols, r)) for r in cur.fetchall()]

        rows_by_visit = {r["visit_id"]: r for r in rows}
        # Latitude/longitude correctly parsed from the packed string
        assert rows_by_visit["1"]["latitude"] == pytest.approx(-1.0000)
        assert rows_by_visit["1"]["longitude"] == pytest.approx(35.0000)
        # Distance from prev: visit 1 = NULL, visits 2 & 3 ≈ 111m apart
        assert rows_by_visit["1"]["distance_from_prev_case_visit_m"] is None
        assert rows_by_visit["2"]["distance_from_prev_case_visit_m"] == pytest.approx(111, abs=2)
        assert rows_by_visit["3"]["distance_from_prev_case_visit_m"] == pytest.approx(111, abs=2)

    def test_gps_transforms_handle_missing_or_malformed(self, db):
        """Missing or malformed GPS strings yield NULL lat/lon (not crashes,
        not zero). Sparse-GPS-friendly all the way through."""
        from commcare_connect.workflow.data_access import PipelineDataAccess

        self._seed_packed_gps(
            20002,
            [
                (1, "m1", "", "2024-01-10T09:00:00"),  # empty
                (2, "m1", "notanumber", "2024-01-10T10:00:00"),  # malformed
                (3, "m1", "-1.0 35.0", "2024-01-10T11:00:00"),  # ok, only 2 tokens
            ],
        )

        schema = {
            "data_source": {"type": "connect_csv"},
            "grouping_key": "username",
            "terminal_stage": "visit_level",
            "fields": [
                {"name": "latitude", "path": "form.meta.location", "aggregation": "first", "transform": "gps_lat"},
                {"name": "longitude", "path": "form.meta.location", "aggregation": "first", "transform": "gps_lon"},
            ],
        }
        access = type("_Fake", (PipelineDataAccess,), {"__init__": lambda self: None})()
        config = access._schema_to_config(schema, definition_id=20002)

        from commcare_connect.labs.analysis.backends.sql.query_builder import build_visit_extraction_query

        query, _ = build_visit_extraction_query(config, opportunity_id=20002)

        with connection.cursor() as cur:
            cur.execute(query)
            cols = [c[0] for c in cur.description]
            rows = [dict(zip(cols, r)) for r in cur.fetchall()]

        rows_by_visit = {r["visit_id"]: r for r in rows}
        # Empty → NULL
        assert rows_by_visit["1"]["latitude"] is None
        assert rows_by_visit["1"]["longitude"] is None
        # Malformed → NULL (regex rejects non-numeric)
        assert rows_by_visit["2"]["latitude"] is None
        # Well-formed even with only 2 tokens → parsed
        assert rows_by_visit["3"]["latitude"] == pytest.approx(-1.0)
        assert rows_by_visit["3"]["longitude"] == pytest.approx(35.0)


class TestWindowFieldValidation:
    """Validation of WindowFieldComputation construction + config integration."""

    def test_lag_haversine_requires_lat_lon(self):
        with pytest.raises(ValueError, match="lat_field and lon_field"):
            WindowFieldComputation(
                name="d",
                operation="lag_haversine",
                partition_by="mother_case_id",
                order_by="visit_datetime",
                lat_field="",
                lon_field="lon",
            )

    def test_lag_haversine_requires_partition_by(self):
        with pytest.raises(ValueError, match="partition_by"):
            WindowFieldComputation(
                name="d",
                operation="lag_haversine",
                partition_by="",
                order_by="visit_datetime",
                lat_field="lat",
                lon_field="lon",
            )

    def test_unknown_operation_rejected(self):
        with pytest.raises(ValueError, match="unknown operation"):
            WindowFieldComputation(
                name="d",
                operation="not_a_real_op",  # type: ignore[arg-type]
                partition_by="x",
                order_by="y",
                lat_field="lat",
                lon_field="lon",
            )

    def test_config_validates_window_field_references(self):
        """A WindowFieldComputation that references a non-existent extracted
        field must fail at config construction (not at query time)."""
        with pytest.raises(ValueError, match="references"):
            AnalysisPipelineConfig(
                grouping_key="username",
                terminal_stage=CacheStage.VISIT_LEVEL,
                fields=[
                    FieldComputation(name="latitude", path="form.lat", aggregation="first"),
                    # Missing 'longitude' field — referenced by window field below
                ],
                window_fields=[
                    WindowFieldComputation(
                        name="d",
                        operation="lag_haversine",
                        partition_by="mother_case_id",  # also missing
                        order_by="visit_datetime",  # also missing
                        lat_field="latitude",
                        lon_field="longitude",  # missing
                    ),
                ],
            )

    def test_config_accepts_base_columns_as_references(self):
        """visit_datetime / visit_date / etc. are base columns on
        labs_raw_visit_cache and are valid references without being
        in fields[]."""
        # Should NOT raise
        AnalysisPipelineConfig(
            grouping_key="username",
            terminal_stage=CacheStage.VISIT_LEVEL,
            fields=[
                FieldComputation(name="latitude", path="form.lat", aggregation="first"),
                FieldComputation(name="longitude", path="form.lon", aggregation="first"),
                FieldComputation(name="mother_case_id", path="form.case.@case_id", aggregation="first"),
            ],
            window_fields=[
                WindowFieldComputation(
                    name="d",
                    operation="lag_haversine",
                    partition_by="mother_case_id",
                    order_by="visit_date",  # base column, no field def needed
                    lat_field="latitude",
                    lon_field="longitude",
                ),
            ],
        )
