# Generated by Django 5.2.12 on 2026-04-20 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyntheticOpportunity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("opportunity_id", models.IntegerField(db_index=True, unique=True)),
                ("label", models.CharField(blank=True, max_length=200)),
                (
                    "gdrive_folder_id",
                    models.CharField(
                        help_text="Google Drive folder ID containing the opp's fixture JSON files.", max_length=200
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="synthetic_opportunities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Synthetic opportunity",
                "verbose_name_plural": "Synthetic opportunities",
                "db_table": "labs_synthetic_opportunity",
                "ordering": ["-updated_at"],
            },
        ),
    ]
