# Generated by Django 5.2.12 on 2026-05-24 15:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synthetic", "0002_usersyntheticdataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="syntheticopportunity",
            name="allowed_domains",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="Email-domain allowlist for labs-only opps (e.g. ['@dimagi.com']). Empty means no domain restriction beyond view_synthetic_opps being on.",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="syntheticopportunity",
            name="labs_only",
            field=models.BooleanField(
                default=False,
                help_text="If true, this opp has no real Connect opp behind it and is surfaced only into labs_context for opted-in users whose email domain matches allowed_domains.",
            ),
        ),
        migrations.AddField(
            model_name="syntheticopportunity",
            name="org_name",
            field=models.CharField(
                blank=True,
                help_text="Display-only org name for labs-only opps. Ignored when labs_only=False.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="syntheticopportunity",
            name="program_name",
            field=models.CharField(
                blank=True,
                help_text="Display-only program name for labs-only opps. Ignored when labs_only=False.",
                max_length=200,
            ),
        ),
    ]
