# Generated by Django 5.2.12 on 2026-06-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synthetic", "0004_labslocalrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="syntheticopportunity",
            name="program_id",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Labs-only program this opp belongs to (reserved >= 10_000 range). When unset, the opp is its own program (program_id = opportunity_id). Set it to file several opps (e.g. a study + its service-delivery opp) under one program. Ignored when labs_only=False.",
                null=True,
            ),
        ),
    ]
