# Generated by Django 5.2.12 on 2026-06-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synthetic", "0005_syntheticopportunity_program_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="syntheticopportunity",
            name="visit_count",
            field=models.IntegerField(
                blank=True,
                help_text="Cached count of this opp's synthetic user_visits, shown in the labs-context opportunity picker. Null = not yet computed (picker falls back to 0). Set at generation and refreshable via the refresh_synthetic_visit_counts management command.",
                null=True,
            ),
        ),
    ]
