# Generated by Django 5.2.12 on 2026-09-16 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("labs", "0023_labsorg"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgConnectSlug",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.CharField(max_length=120, unique=True)),
                ("why", models.TextField()),
                ("source_row", models.IntegerField(blank=True, null=True)),
                ("imported_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="connect_slugs", to="labs.labsorg"
                    ),
                ),
            ],
            options={
                "verbose_name": "Connect slug attribution",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="OrgProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("has_used_connect", models.BooleanField(blank=True, null=True)),
                ("year_established", models.IntegerField(blank=True, null=True)),
                ("team_size", models.IntegerField(blank=True, null=True)),
                ("flws_managed", models.IntegerField(blank=True, null=True)),
                ("countries", models.JSONField(blank=True, default=list)),
                ("regions", models.JSONField(blank=True, default=list)),
                ("sectors", models.JSONField(blank=True, default=list)),
                ("website", models.CharField(blank=True, default="", max_length=500)),
                ("office_address", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("msa_link", models.CharField(blank=True, default="", max_length=500)),
                ("work_order_link", models.CharField(blank=True, default="", max_length=500)),
                ("joined_at", models.DateField(blank=True, db_index=True, null=True)),
                ("joined_basis", models.CharField(blank=True, default="", max_length=200)),
                ("country_iso3", models.CharField(blank=True, db_index=True, default="", max_length=3)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                (
                    "location_precision",
                    models.CharField(
                        blank=True,
                        choices=[("city", "city"), ("region", "region"), ("country", "country")],
                        default="",
                        max_length=8,
                    ),
                ),
                ("location_label", models.CharField(blank=True, default="", max_length=160)),
                ("source_row", models.IntegerField(blank=True, null=True)),
                ("imported_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marketplace_profile",
                        to="labs.labsorg",
                    ),
                ),
            ],
            options={
                "verbose_name": "organisation profile",
            },
        ),
        migrations.CreateModel(
            name="OrgContact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(blank=True, default="", max_length=200)),
                ("role_title", models.CharField(blank=True, default="", max_length=200)),
                ("is_main_poc", models.BooleanField(default=False)),
                ("email", models.EmailField(max_length=320)),
                ("phone", models.CharField(blank=True, default="", max_length=64)),
                ("notes", models.TextField(blank=True, default="")),
                ("source_row", models.IntegerField(blank=True, null=True)),
                ("imported_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="contacts", to="labs.labsorg"
                    ),
                ),
            ],
            options={
                "ordering": ["-is_main_poc", "full_name"],
                "constraints": [models.UniqueConstraint(fields=("org", "email"), name="uniq_contact_email_per_org")],
            },
        ),
    ]
