# Generated by Django 5.2.12 on 2026-09-17 01:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0002_carry_pulse_partners"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orgprofile",
            name="sectors",
        ),
    ]
