# Generated by Django 5.2.12 on 2026-09-17 06:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0003_remove_orgprofile_sectors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orgprofile",
            name="flws_managed",
        ),
    ]
