# Generated by Django 6.0.8 on 2026-10-05 12:00

from django.db import migrations, models


def backfill(apps, schema_editor):
    """Resolve every existing profile now, rather than leaving the map on head
    offices until the next daily import. Reads only what the profile already
    holds; the import overwrites it from the sheet on its next run."""
    from connect_labs.pulse.hq_location import operating_areas

    OrgProfile = apps.get_model("marketplace", "OrgProfile")
    for profile in OrgProfile.objects.all().only("id", "countries", "regions"):
        areas = operating_areas(profile.countries or [], "; ".join(profile.regions or []))
        if areas:
            OrgProfile.objects.filter(pk=profile.pk).update(operating_areas=areas)


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_org_membership"),
        ("admin_boundaries", "0003_adminboundary_extra_adminboundary_parent_boundary_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgprofile",
            name="operating_areas",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop, hints={"run_on_secondary": False}),
    ]
