# Generated by Django 5.2.12 on 2026-07-25 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'supply_bid',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rutf', 'RUTF'), ('therapeutic_milk', 'Therapeutic milk'), ('transport', 'Road transport'), ('warehousing', 'Warehousing')], max_length=32)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='cartons', max_length=32)),
                ('delivery_country', models.CharField(max_length=2)),
                ('delivery_place', models.CharField(max_length=128)),
                ('delivery_deadline', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'supply_lot',
            },
        ),
        migrations.CreateModel(
            name='SupplierOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=64)),
                ('country', models.CharField(max_length=2)),
                ('hq_city', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('contact_name', models.CharField(blank=True, max_length=128)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('gln', models.CharField(blank=True, max_length=13)),
                ('gs1_company_prefix', models.CharField(blank=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'supply_supplier_org',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('obj_type', models.CharField(max_length=64)),
                ('obj_id', models.CharField(max_length=64)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supply_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EOIRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('brief', models.TextField(blank=True)),
                ('categories', models.JSONField(default=list)),
                ('opens_at', models.DateField(blank=True, null=True)),
                ('closes_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supply_eoi_round',
            },
        ),
        migrations.CreateModel(
            name='EOISubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.JSONField(default=list)),
                ('commitments', models.JSONField(default=dict)),
                ('profile_snapshot', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('qualified', 'Qualified'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='supply.eoiround')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eoi_submissions', to='supply.supplierorg')),
            ],
            options={
                'db_table': 'supply_eoi_submission',
            },
        ),
        migrations.CreateModel(
            name='EOIReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisions', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='supply.eoisubmission')),
            ],
            options={
                'db_table': 'supply_eoi_review',
            },
        ),
        migrations.CreateModel(
            name='LotBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_bids', to='supply.bid')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_bids', to='supply.lot')),
            ],
            options={
                'db_table': 'supply_lot_bid',
            },
        ),
        migrations.CreateModel(
            name='BidScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_score', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lot_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='supply.lotbid')),
            ],
            options={
                'db_table': 'supply_bid_score',
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='supply.lot')),
                ('lot_bid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='supply.lotbid')),
            ],
            options={
                'db_table': 'supply_award',
            },
        ),
        migrations.CreateModel(
            name='RFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('brief', models.TextField(blank=True)),
                ('categories', models.JSONField(default=list)),
                ('countries', models.JSONField(default=list)),
                ('bid_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('awarded', 'Awarded')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supply_rfp',
            },
        ),
        migrations.AddField(
            model_name='lot',
            name='rfp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='supply.rfp'),
        ),
        migrations.AddField(
            model_name='bid',
            name='rfp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='supply.rfp'),
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('procurement_admin', 'Procurement Admin'), ('reviewer', 'Reviewer'), ('gov_observer', 'Gov Observer'), ('funder', 'Funder')], max_length=32)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supply_staff_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supply_staff_role',
            },
        ),
        migrations.CreateModel(
            name='SupplierMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supply_membership', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='supply.supplierorg')),
            ],
            options={
                'db_table': 'supply_supplier_member',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rutf', 'RUTF'), ('therapeutic_milk', 'Therapeutic milk'), ('transport', 'Road transport'), ('warehousing', 'Warehousing')], max_length=32)),
                ('granted_at', models.DateField()),
                ('expires_at', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=16)),
                ('source_submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='supply.eoisubmission')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='supply.supplierorg')),
            ],
            options={
                'db_table': 'supply_qualification',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(max_length=64)),
                ('issuer', models.CharField(blank=True, max_length=128)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document_name', models.CharField(blank=True, max_length=255)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='supply.supplierorg')),
            ],
            options={
                'db_table': 'supply_certification',
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='supply.supplierorg'),
        ),
        migrations.AddConstraint(
            model_name='lotbid',
            constraint=models.UniqueConstraint(fields=('bid', 'lot'), name='uniq_lotbid_per_bid_lot'),
        ),
        migrations.AddConstraint(
            model_name='bidscore',
            constraint=models.UniqueConstraint(fields=('lot_bid', 'reviewer'), name='uniq_score_per_reviewer'),
        ),
        migrations.AddConstraint(
            model_name='eoisubmission',
            constraint=models.UniqueConstraint(fields=('org', 'round'), name='uniq_submission_per_org_round'),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(fields=('org', 'rfp'), name='uniq_bid_per_org_rfp'),
        ),
    ]
