# Generated by Django 5.2.12 on 2026-07-25 18:37

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appropriation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funder_name', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=255)),
                ('fiscal_year', models.CharField(blank=True, max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('iati_activity_id', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'db_table': 'supply_appropriation',
            },
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('prefix', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='supply.supplierorg')),
            ],
            options={
                'db_table': 'supply_api_token',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='cartons', max_length=32)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('iati_activity_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appropriation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='supply.appropriation')),
                ('award', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='supply.award')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='supply.supplierorg')),
            ],
            options={
                'db_table': 'supply_contract',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('asn_reference', models.CharField(blank=True, max_length=64)),
                ('waypoints', models.JSONField(default=list)),
                ('route', django.contrib.gis.db.models.fields.LineStringField(blank=True, geography=True, null=True, srid=4326)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='cartons', max_length=32)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('confirmed', 'Confirmed')], default='planned', max_length=16)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('eta', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='supply.contract')),
            ],
            options={
                'db_table': 'supply_shipment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtin', models.CharField(max_length=14)),
                ('batch_lot', models.CharField(blank=True, max_length=32)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='cartons', max_length=32)),
                ('sscc', models.CharField(blank=True, max_length=18)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='supply.shipment')),
            ],
            options={
                'db_table': 'supply_shipment_line',
            },
        ),
        migrations.CreateModel(
            name='SupplyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('object', 'Object'), ('aggregation', 'Aggregation'), ('transformation', 'Transformation')], default='object', max_length=24)),
                ('biz_step', models.CharField(choices=[('commissioning', 'Commissioning'), ('packing', 'Packing'), ('loading', 'Loading'), ('departing', 'Departing'), ('arriving', 'Arriving'), ('receiving', 'Receiving'), ('inspecting', 'Inspecting'), ('storing', 'Storing')], max_length=24)),
                ('disposition', models.CharField(blank=True, max_length=32)),
                ('event_time', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('epc_list', models.JSONField(default=list)),
                ('quantity_list', models.JSONField(default=list)),
                ('biz_transactions', models.JSONField(default=dict)),
                ('source_tier', models.CharField(choices=[('epcis', 'Epcis'), ('asn', 'Asn'), ('checkin', 'Checkin'), ('portal', 'Portal')], max_length=16)),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('raw', models.JSONField(default=dict)),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='supply.supplierorg')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='supply.shipment')),
            ],
            options={
                'db_table': 'supply_event',
                'ordering': ['event_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='supply.shipment')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancies', to='supply.supplyevent')),
            ],
            options={
                'db_table': 'supply_discrepancy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('factory', 'Factory'), ('port', 'Port'), ('warehouse', 'Warehouse'), ('distribution_hub', 'Distribution Hub'), ('delivery_point', 'Delivery Point')], max_length=32)),
                ('country', models.CharField(max_length=2)),
                ('gln', models.CharField(blank=True, max_length=13)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='supply.supplierorg')),
            ],
            options={
                'db_table': 'supply_node',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='supplyevent',
            name='read_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='supply.supplynode'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='supply.supplynode'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='supply.supplynode'),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('depart', 'Depart'), ('arrive', 'Arrive')], max_length=16)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('planned_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_at', models.DateTimeField(blank=True, null=True)),
                ('actual_at', models.DateTimeField(blank=True, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='supply.shipment')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestones', to='supply.supplynode')),
            ],
            options={
                'db_table': 'supply_milestone',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplyevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('org', 'external_id'), name='uniq_event_external_id_per_org'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.UniqueConstraint(fields=('shipment', 'node', 'kind', 'sequence'), name='uniq_milestone_per_leg'),
        ),
    ]
