# Generated by Django 5.2.12 on 2026-07-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_appropriation_apitoken_contract_shipment_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='qualification',
            constraint=models.UniqueConstraint(fields=('org', 'category'), name='uniq_qualification_per_org_category'),
        ),
    ]
