# Generated by Django 5.2.12 on 2026-07-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0005_supplynode_catchment_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childoutcome",
            name="discharge_status",
            field=models.CharField(
                choices=[
                    ("recovered", "Recovered"),
                    ("defaulted", "Defaulted"),
                    ("died", "Died"),
                    ("transferred", "Transferred to inpatient care"),
                    ("non_response", "Non Response"),
                    ("in_treatment", "In Treatment"),
                ],
                default="in_treatment",
                max_length=16,
            ),
        ),
    ]
