# Generated by Django 5.2.12 on 2026-07-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply", "0006_alter_childoutcome_discharge_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualification",
            name="verify_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
