# Generated by Django 5.2.12 on 2026-09-12 14:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Round",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("program_id", models.IntegerField(db_index=True)),
                ("label", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "draft"), ("open", "open"), ("closed", "closed"), ("awarded", "awarded")],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("lines", models.JSONField(blank=True, default=list)),
                ("delivery_point", models.JSONField(blank=True, default=dict)),
                ("response_deadline", models.DateField(blank=True, null=True)),
                ("reminder_interval_days", models.IntegerField(blank=True, null=True)),
                ("shelf_life_months_minimum", models.IntegerField(blank=True, null=True)),
                ("notes_to_supplier", models.TextField(blank=True, default="")),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Commodity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scope_key", models.CharField(db_index=True, max_length=64)),
                ("slug", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, default="", max_length=32)),
                ("base_unit", models.CharField(blank=True, default="", max_length=32)),
                ("pack_unit", models.CharField(blank=True, default="", max_length=32)),
                ("base_per_pack", models.IntegerField(blank=True, null=True)),
                ("base_unit_grams", models.IntegerField(blank=True, null=True)),
                ("shelf_life_months_minimum", models.IntegerField(blank=True, null=True)),
                ("spec_requirements", models.JSONField(blank=True, default=list)),
                ("course_definition", models.JSONField(blank=True, default=dict)),
                ("spec_reference", models.CharField(blank=True, default="", max_length=255)),
                ("unicef_material_number", models.CharField(blank=True, default="", max_length=32)),
            ],
            options={
                "verbose_name_plural": "commodities",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(fields=("scope_key", "slug"), name="uniq_commodity_scope_slug")
                ],
            },
        ),
        migrations.CreateModel(
            name="Award",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("decided_on", models.DateField(blank=True, null=True)),
                ("decided_by", models.CharField(blank=True, default="", max_length=255)),
                ("rationale", models.TextField(blank=True, default="")),
                ("comparison_snapshot", models.JSONField(blank=True, default=dict)),
                ("provisional", models.BooleanField(default=False)),
                (
                    "assumed_buyer_of_record",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("programme_org", "programme org"),
                            ("partner_org", "partner org"),
                            ("agency", "agency"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="awards", to="supply_chain.commodity"
                    ),
                ),
            ],
            options={
                "ordering": ["-decided_on", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("we_recorded", "we recorded"),
                            ("partner_reported", "partner reported"),
                            ("supplier_reported", "supplier reported"),
                            ("commcare_form", "commcare form"),
                            ("connect_visit", "connect visit"),
                            ("document", "document"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("program_id", models.IntegerField(db_index=True)),
                (
                    "buyer_of_record",
                    models.CharField(
                        choices=[
                            ("programme_org", "programme org"),
                            ("partner_org", "partner org"),
                            ("agency", "agency"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("signed_on", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("placed", "placed"),
                            ("confirmed", "confirmed"),
                            ("part_received", "part received"),
                            ("received", "received"),
                            ("closed", "closed"),
                            ("cancelled", "cancelled"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("quantity", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("quantity_unit", models.CharField(blank=True, default="", max_length=32)),
                ("unit_price", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("unit_price_unit", models.CharField(blank=True, default="", max_length=24)),
                (
                    "freight_basis",
                    models.CharField(
                        choices=[
                            ("included", "included"),
                            ("excluded", "excluded"),
                            ("not_specified", "not specified"),
                        ],
                        default="not_specified",
                        max_length=16,
                    ),
                ),
                ("freight_amount", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                (
                    "duties_basis",
                    models.CharField(
                        choices=[
                            ("included", "included"),
                            ("excluded", "excluded"),
                            ("not_specified", "not specified"),
                        ],
                        default="not_specified",
                        max_length=16,
                    ),
                ),
                ("duties_amount", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                (
                    "vat_basis",
                    models.CharField(
                        choices=[
                            ("included", "included"),
                            ("excluded", "excluded"),
                            ("not_specified", "not specified"),
                        ],
                        default="not_specified",
                        max_length=16,
                    ),
                ),
                ("vat_amount", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("duty_relief_claimed", models.BooleanField(default=False)),
                ("incoterm", models.CharField(blank=True, default="", max_length=16)),
                ("promised_lead_time_days", models.IntegerField(blank=True, null=True)),
                (
                    "award",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="supply_chain.award",
                    ),
                ),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="supply_chain.commodity",
                    ),
                ),
            ],
            options={
                "ordering": ["-signed_on", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("we_recorded", "we recorded"),
                            ("partner_reported", "partner reported"),
                            ("supplier_reported", "supplier reported"),
                            ("commcare_form", "commcare form"),
                            ("connect_visit", "connect visit"),
                            ("document", "document"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("program_id", models.IntegerField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("purchase_order", "purchase order"),
                            ("order_confirmation", "order confirmation"),
                            ("certificate_of_analysis", "certificate of analysis"),
                            ("certificate_of_conformity", "certificate of conformity"),
                            ("duty_exemption", "duty exemption"),
                            ("dispatch_note", "dispatch note"),
                            ("goods_received_note", "goods received note"),
                            ("invoice", "invoice"),
                            ("proof_of_payment", "proof of payment"),
                            ("stock_report", "stock report"),
                            ("other", "other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("filename", models.CharField(blank=True, default="", max_length=255)),
                ("content_type", models.CharField(blank=True, default="", max_length=128)),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("storage_key", models.CharField(blank=True, default="", max_length=512)),
                ("external_url", models.URLField(blank=True, default="", max_length=1024)),
                ("sha256", models.CharField(blank=True, default="", max_length=64)),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="supply_chain.contract",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="duty_relief_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="supply_chain.document",
            ),
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("we_recorded", "we recorded"),
                            ("partner_reported", "partner reported"),
                            ("supplier_reported", "supplier reported"),
                            ("commcare_form", "commcare form"),
                            ("connect_visit", "connect visit"),
                            ("document", "document"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("issued_on", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "received"),
                            ("queried", "queried"),
                            ("approved", "approved"),
                            ("part_paid", "part paid"),
                            ("paid", "paid"),
                            ("rejected", "rejected"),
                        ],
                        default="received",
                        max_length=16,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("amount", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("quantity_billed", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("quantity_unit", models.CharField(blank=True, default="", max_length=32)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="supply_chain.contract",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_on", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="supply_chain.invoice",
            ),
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scope_key", models.CharField(db_index=True, max_length=64)),
                ("sku", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("manufacturer", models.CharField(blank=True, default="", max_length=255)),
                ("base_unit", models.CharField(blank=True, default="", max_length=32)),
                ("pack_unit", models.CharField(blank=True, default="", max_length=32)),
                ("base_per_pack", models.IntegerField(blank=True, null=True)),
                ("pack_per_case", models.IntegerField(blank=True, null=True)),
                ("base_unit_grams", models.IntegerField(blank=True, null=True)),
                ("shelf_life_months", models.IntegerField(blank=True, null=True)),
                ("gtin_base", models.CharField(blank=True, default="", max_length=14)),
                ("gtin_pack", models.CharField(blank=True, default="", max_length=14)),
                ("gtin_case", models.CharField(blank=True, default="", max_length=14)),
                ("gpc_brick", models.CharField(blank=True, default="", max_length=16)),
                ("spec_attributes", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("discontinued", "discontinued")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="items", to="supply_chain.commodity"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="supply_chain.item",
            ),
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scope_key", models.CharField(db_index=True, max_length=64)),
                ("slug", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("programme_org", "programme org"),
                            ("partner_org", "partner org"),
                            ("supplier", "supplier"),
                            ("agency", "agency"),
                        ],
                        max_length=32,
                    ),
                ),
                ("connect_organization_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("roles", models.JSONField(blank=True, default=list)),
                ("country", models.CharField(blank=True, default="", max_length=2)),
                ("contacts", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name_plural": "parties",
                "ordering": ["name"],
                "constraints": [models.UniqueConstraint(fields=("scope_key", "slug"), name="uniq_party_scope_slug")],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="recorded_by_party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="supply_chain.party",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="recorded_by_party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="supply_chain.party",
            ),
        ),
        migrations.CreateModel(
            name="Distribution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("we_recorded", "we recorded"),
                            ("partner_reported", "partner reported"),
                            ("supplier_reported", "supplier reported"),
                            ("commcare_form", "commcare form"),
                            ("connect_visit", "connect visit"),
                            ("document", "document"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("program_id", models.IntegerField(db_index=True)),
                ("opportunity_id", models.IntegerField(db_index=True)),
                ("distributed_on", models.DateField(db_index=True)),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                (
                    "recorded_by_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="supply_chain.party",
                    ),
                ),
            ],
            options={
                "ordering": ["-distributed_on", "-id"],
            },
        ),
        migrations.AddField(
            model_name="contract",
            name="buyer_party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="contracts", to="supply_chain.party"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="recorded_by_party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="supply_chain.party",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("we_recorded", "we recorded"),
                            ("partner_reported", "partner reported"),
                            ("supplier_reported", "supplier reported"),
                            ("commcare_form", "commcare form"),
                            ("connect_visit", "connect visit"),
                            ("document", "document"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("paid_on", models.DateField()),
                ("amount", models.DecimalField(decimal_places=4, max_digits=18)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("method", models.CharField(blank=True, default="", max_length=32)),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="supply_chain.invoice"
                    ),
                ),
                (
                    "recorded_by_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="supply_chain.party",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_on"],
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("as_quoted_amount", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("as_quoted_unit", models.CharField(blank=True, default="", max_length=24)),
                ("as_quoted_currency", models.CharField(default="USD", max_length=3)),
                ("quantity_basis", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("quantity_basis_unit", models.CharField(blank=True, default="", max_length=32)),
                ("pack_spec_source", models.CharField(blank=True, default="not_stated", max_length=24)),
                ("base_per_pack_stated", models.IntegerField(blank=True, null=True)),
                ("base_unit_grams_stated", models.IntegerField(blank=True, null=True)),
                ("freight_basis", models.CharField(blank=True, default="not_specified", max_length=16)),
                ("freight_amount", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("duties_basis", models.CharField(blank=True, default="not_specified", max_length=16)),
                ("duties_amount", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("fx_rate_to_usd", models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ("shelf_life_months_stated", models.IntegerField(blank=True, null=True)),
                ("moq", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("moq_unit", models.CharField(blank=True, default="", max_length=32)),
                ("lead_time_days", models.IntegerField(blank=True, null=True)),
                ("validity_until", models.DateField(blank=True, null=True)),
                ("incoterm", models.CharField(blank=True, default="", max_length=16)),
                ("stated_spec", models.JSONField(blank=True, default=dict)),
                ("received_on", models.DateField(blank=True, null=True)),
                ("voided", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="quotes", to="supply_chain.commodity"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotes",
                        to="supply_chain.item",
                    ),
                ),
                (
                    "superseded_by",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="supply_chain.quote",
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="quotes", to="supply_chain.round"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="award",
            name="quote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="awards", to="supply_chain.quote"
            ),
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("we_recorded", "we recorded"),
                            ("partner_reported", "partner reported"),
                            ("supplier_reported", "supplier reported"),
                            ("commcare_form", "commcare form"),
                            ("connect_visit", "connect visit"),
                            ("document", "document"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("received_on", models.DateField()),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="supply_chain.contract",
                    ),
                ),
                (
                    "recorded_by_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="supply_chain.party",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_on", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="supply_chain.receipt",
            ),
        ),
        migrations.CreateModel(
            name="ReceiptLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("batch", models.CharField(blank=True, default="", max_length=64)),
                ("expiry", models.DateField(blank=True, null=True)),
                ("quantity_accepted", models.DecimalField(decimal_places=4, max_digits=18)),
                ("quantity_rejected", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=18)),
                ("rejection_reason", models.CharField(blank=True, default="", max_length=255)),
                ("quantity_unit", models.CharField(max_length=32)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="supply_chain.item",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="supply_chain.receipt"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contract",
            name="round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="supply_chain.round",
            ),
        ),
        migrations.AddField(
            model_name="award",
            name="round",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="awards", to="supply_chain.round"
            ),
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("we_recorded", "we recorded"),
                            ("partner_reported", "partner reported"),
                            ("supplier_reported", "supplier reported"),
                            ("commcare_form", "commcare form"),
                            ("connect_visit", "connect visit"),
                            ("document", "document"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("sscc", models.CharField(blank=True, default="", max_length=18)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "planned"),
                            ("dispatched", "dispatched"),
                            ("in_transit", "in transit"),
                            ("at_customs", "at customs"),
                            ("cleared", "cleared"),
                            ("delivered", "delivered"),
                            ("lost", "lost"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("dispatched_on", models.DateField(blank=True, null=True)),
                ("expected_on", models.DateField(blank=True, null=True)),
                ("carrier", models.CharField(blank=True, default="", max_length=255)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="supply_chain.contract",
                    ),
                ),
                (
                    "recorded_by_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="supply_chain.party",
                    ),
                ),
            ],
            options={
                "ordering": ["-dispatched_on", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="receipt",
            name="shipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipts",
                to="supply_chain.shipment",
            ),
        ),
        migrations.CreateModel(
            name="Movement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("we_recorded", "we recorded"),
                            ("partner_reported", "partner reported"),
                            ("supplier_reported", "supplier reported"),
                            ("commcare_form", "commcare form"),
                            ("connect_visit", "connect visit"),
                            ("document", "document"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("program_id", models.IntegerField(db_index=True)),
                ("opportunity_id", models.IntegerField(blank=True, db_index=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("receipt", "receipt"),
                            ("issue", "issue"),
                            ("transfer", "transfer"),
                            ("distribution", "distribution"),
                            ("consumption", "consumption"),
                            ("adjustment", "adjustment"),
                            ("loss", "loss"),
                            ("expiry", "expiry"),
                            ("return", "return"),
                        ],
                        max_length=16,
                    ),
                ),
                ("occurred_on", models.DateField(db_index=True)),
                ("batch", models.CharField(blank=True, default="", max_length=64)),
                ("expiry", models.DateField(blank=True, null=True)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("quantity_unit", models.CharField(max_length=32)),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="supply_chain.commodity",
                    ),
                ),
                (
                    "distribution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="supply_chain.distribution",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="supply_chain.item",
                    ),
                ),
                (
                    "recorded_by_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="supply_chain.party",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="supply_chain.receipt",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="supply_chain.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_on", "-id"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="shipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="supply_chain.shipment",
            ),
        ),
        migrations.CreateModel(
            name="ShipmentLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("batch", models.CharField(blank=True, default="", max_length=64)),
                ("expiry", models.DateField(blank=True, null=True)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("quantity_unit", models.CharField(max_length=32)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="supply_chain.item",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="supply_chain.shipment"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("we_recorded", "we recorded"),
                            ("partner_reported", "partner reported"),
                            ("supplier_reported", "supplier reported"),
                            ("commcare_form", "commcare form"),
                            ("connect_visit", "connect visit"),
                            ("document", "document"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("program_id", models.IntegerField(db_index=True)),
                ("opportunity_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("batch", models.CharField(blank=True, default="", max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("self_reported", "self reported"),
                            ("physical_count", "physical count"),
                            ("override", "override"),
                        ],
                        max_length=16,
                    ),
                ),
                ("counted_on", models.DateField(db_index=True)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("quantity_unit", models.CharField(max_length=32)),
                ("reason", models.TextField(blank=True, default="")),
                ("form_submission_id", models.CharField(blank=True, default="", max_length=64)),
                ("visit_id", models.CharField(blank=True, default="", max_length=64)),
                ("connect_username", models.CharField(blank=True, db_index=True, default="", max_length=150)),
                (
                    "adjustment_movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="caused_by_count",
                        to="supply_chain.movement",
                    ),
                ),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_counts",
                        to="supply_chain.commodity",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_counts",
                        to="supply_chain.item",
                    ),
                ),
                (
                    "recorded_by_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="supply_chain.party",
                    ),
                ),
            ],
            options={
                "ordering": ["-counted_on", "-id"],
            },
        ),
        migrations.AddField(
            model_name="movement",
            name="stock_count",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="supply_chain.stockcount",
            ),
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scope_key", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(blank=True, default="", max_length=32)),
                ("country", models.CharField(blank=True, default="", max_length=2)),
                ("city", models.CharField(blank=True, default="", max_length=128)),
                ("status", models.CharField(blank=True, default="identified", max_length=32)),
                ("contacts", models.JSONField(blank=True, default=list)),
                ("qualifications", models.JSONField(blank=True, default=list)),
                ("connect_organization_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_roles",
                        to="supply_chain.party",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="quote",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="quotes", to="supply_chain.supplier"
            ),
        ),
        migrations.CreateModel(
            name="Outreach",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("channel", models.CharField(blank=True, default="manual", max_length=16)),
                ("sent_on", models.DateField(blank=True, null=True)),
                ("responded", models.BooleanField(default=False)),
                ("response_kind", models.CharField(blank=True, default="", max_length=16)),
                ("last_reminder_on", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="outreach", to="supply_chain.round"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outreach",
                        to="supply_chain.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "outreach",
                "ordering": ["-sent_on", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="supply_chain.supplier",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="contracts", to="supply_chain.supplier"
            ),
        ),
        migrations.AddField(
            model_name="award",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="awards", to="supply_chain.supplier"
            ),
        ),
        migrations.CreateModel(
            name="SupplyPoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("we_recorded", "we recorded"),
                            ("partner_reported", "partner reported"),
                            ("supplier_reported", "supplier reported"),
                            ("commcare_form", "commcare form"),
                            ("connect_visit", "connect visit"),
                            ("document", "document"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("program_id", models.IntegerField(db_index=True)),
                ("opportunity_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("slug", models.SlugField(max_length=96)),
                ("name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("central_store", "central store"),
                            ("regional_store", "regional store"),
                            ("facility", "facility"),
                            ("user_held", "user held"),
                            ("supplier_site", "supplier site"),
                            ("in_transit", "in transit"),
                            ("customs", "customs"),
                        ],
                        max_length=24,
                    ),
                ),
                ("connect_username", models.CharField(blank=True, db_index=True, default="", max_length=150)),
                ("connect_user_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("admin_area", models.CharField(blank=True, default="", max_length=255)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("min_months_of_stock", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("max_months_of_stock", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("inactive", "inactive")], default="active", max_length=16
                    ),
                ),
                (
                    "managed_by_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supply_points",
                        to="supply_chain.party",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="supply_chain.supplypoint",
                    ),
                ),
                (
                    "recorded_by_party",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="supply_chain.party",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="stockcount",
            name="supply_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="stock_counts", to="supply_chain.supplypoint"
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="supply_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="receipts", to="supply_chain.supplypoint"
            ),
        ),
        migrations.AddField(
            model_name="movement",
            name="from_supply_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements_out",
                to="supply_chain.supplypoint",
            ),
        ),
        migrations.AddField(
            model_name="movement",
            name="to_supply_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements_in",
                to="supply_chain.supplypoint",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="supply_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="supply_chain.supplypoint",
            ),
        ),
        migrations.CreateModel(
            name="DistributionLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("connect_username", models.CharField(blank=True, default="", max_length=150)),
                ("batch", models.CharField(blank=True, default="", max_length=64)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("quantity_unit", models.CharField(max_length=32)),
                (
                    "distribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="supply_chain.distribution",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="supply_chain.item",
                    ),
                ),
                (
                    "movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distribution_line",
                        to="supply_chain.movement",
                    ),
                ),
                (
                    "to_supply_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distribution_lines",
                        to="supply_chain.supplypoint",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="distribution",
            name="supply_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="distributions_out",
                to="supply_chain.supplypoint",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="delivery_supply_point",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inbound_contracts",
                to="supply_chain.supplypoint",
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(fields=("scope_key", "sku"), name="uniq_item_scope_sku"),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["round", "commodity"], name="supply_chai_round_i_f205c7_idx"),
        ),
        migrations.AddIndex(
            model_name="outreach",
            index=models.Index(fields=["round", "supplier"], name="supply_chai_round_i_4a8f26_idx"),
        ),
        migrations.AddIndex(
            model_name="supplypoint",
            index=models.Index(fields=["program_id", "kind"], name="supply_chai_program_7cfde2_idx"),
        ),
        migrations.AddConstraint(
            model_name="supplypoint",
            constraint=models.UniqueConstraint(fields=("program_id", "slug"), name="uniq_supply_point_program_slug"),
        ),
        migrations.AddIndex(
            model_name="stockcount",
            index=models.Index(fields=["supply_point", "item", "counted_on"], name="supply_chai_supply__f393cc_idx"),
        ),
        migrations.AddIndex(
            model_name="movement",
            index=models.Index(fields=["program_id", "item", "occurred_on"], name="supply_chai_program_66fa22_idx"),
        ),
        migrations.AddIndex(
            model_name="movement",
            index=models.Index(fields=["to_supply_point", "item"], name="supply_chai_to_supp_3f4a6c_idx"),
        ),
        migrations.AddIndex(
            model_name="movement",
            index=models.Index(fields=["from_supply_point", "item"], name="supply_chai_from_su_afe030_idx"),
        ),
        migrations.AddIndex(
            model_name="movement",
            index=models.Index(fields=["opportunity_id", "kind"], name="supply_chai_opportu_2f7ba9_idx"),
        ),
        migrations.AddConstraint(
            model_name="movement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("from_supply_point__isnull", False), ("to_supply_point__isnull", False), _connector="OR"
                ),
                name="movement_touches_a_point",
            ),
        ),
        migrations.AddConstraint(
            model_name="movement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0), ("kind", "adjustment"), _connector="OR"),
                name="movement_positive_unless_adjustment",
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("storage_key", ""), _negated=True),
                    models.Q(("external_url", ""), _negated=True),
                    _connector="OR",
                ),
                name="document_has_a_location",
            ),
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(fields=["program_id", "status"], name="supply_chai_program_2340ec_idx"),
        ),
    ]
