# Generated by Django 5.2.12 on 2026-09-13 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("supply_chain", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="award",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="supply_chain.award",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="distribution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="supply_chain.distribution",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="supply_chain.item",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="supply_chain.payment",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="supply_chain.quote",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="round",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="supply_chain.round",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="stock_count",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="supply_chain.stockcount",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="kind",
            field=models.CharField(
                choices=[
                    ("purchase_order", "purchase order"),
                    ("order_confirmation", "order confirmation"),
                    ("quotation", "quotation"),
                    ("pro_forma_invoice", "pro forma invoice"),
                    ("certificate_of_analysis", "certificate of analysis"),
                    ("certificate_of_conformity", "certificate of conformity"),
                    ("duty_exemption", "duty exemption"),
                    ("dispatch_note", "dispatch note"),
                    ("goods_received_note", "goods received note"),
                    ("invoice", "invoice"),
                    ("proof_of_payment", "proof of payment"),
                    ("proof_of_delivery", "proof of delivery"),
                    ("specification_sheet", "specification sheet"),
                    ("photo", "photo"),
                    ("stock_report", "stock report"),
                    ("other", "other"),
                ],
                max_length=32,
            ),
        ),
    ]
