# Generated by Django 6.0.8 on 2026-09-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0005_drop_party"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="components",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="item",
            name="one_course_is",
            field=models.CharField(
                blank=True, choices=[("", ""), ("base_unit", "base unit"), ("pack", "pack")], default="", max_length=16
            ),
        ),
    ]
