# Generated by Django 6.0.8 on 2026-09-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0006_item_kits"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="consideration",
            field=models.CharField(
                choices=[("priced", "priced"), ("in_kind", "in kind"), ("bundled", "bundled")],
                default="priced",
                max_length=16,
            ),
        ),
    ]
