# Generated by Django 6.0.8 on 2026-09-23 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0024_workflowschedule_interval_hours"),
        ("supply_chain", "0007_contract_consideration"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="required_documents",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="document",
            name="kind",
            field=models.CharField(
                choices=[
                    ("purchase_order", "purchase order"),
                    ("order_confirmation", "order confirmation"),
                    ("quotation", "quotation"),
                    ("pro_forma_invoice", "pro forma invoice"),
                    ("certificate_of_analysis", "certificate of analysis"),
                    ("certificate_of_conformity", "certificate of conformity"),
                    ("duty_exemption", "duty exemption"),
                    ("dispatch_note", "dispatch note"),
                    ("goods_received_note", "goods received note"),
                    ("invoice", "invoice"),
                    ("proof_of_payment", "proof of payment"),
                    ("proof_of_delivery", "proof of delivery"),
                    ("specification_sheet", "specification sheet"),
                    ("photo", "photo"),
                    ("stock_report", "stock report"),
                    ("airway_bill", "airway bill"),
                    ("bill_of_lading", "bill of lading"),
                    ("packing_list", "packing list"),
                    ("commercial_invoice", "commercial invoice"),
                    ("import_permit", "import permit"),
                    ("customs_declaration", "customs declaration"),
                    ("product_registration", "product registration"),
                    ("other", "other"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="Charge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("we_recorded", "we recorded"),
                            ("partner_reported", "partner reported"),
                            ("supplier_reported", "supplier reported"),
                            ("commcare_form", "commcare form"),
                            ("connect_visit", "connect visit"),
                            ("document", "document"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("customs_duty", "customs duty"),
                            ("customs_fee", "customs fee"),
                            ("clearing", "clearing"),
                            ("inland_freight", "inland freight"),
                            ("storage", "storage"),
                            ("other", "other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=18)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("fx_rate_to_usd", models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ("paid_on", models.DateField(blank=True, null=True)),
                (
                    "payee_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="supply_charges", to="labs.labsorg"
                    ),
                ),
                (
                    "recorded_by_org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="labs.labsorg",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="charges", to="supply_chain.shipment"
                    ),
                ),
            ],
            options={
                "ordering": ["paid_on", "id"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="charge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="supply_chain.charge",
            ),
        ),
    ]
