# Generated by Django 6.0.8 on 2026-09-23 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0024_workflowschedule_interval_hours"),
        ("supply_chain", "0008_import_clearance"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwardApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("technical", "technical"), ("funder", "funder"), ("regulatory", "regulatory")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("requested", "requested"), ("approved", "approved"), ("declined", "declined")],
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("requested_on", models.DateField()),
                ("decided_on", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "approver_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="supply_approvals", to="labs.labsorg"
                    ),
                ),
                (
                    "award",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="approvals", to="supply_chain.award"
                    ),
                ),
            ],
            options={
                "ordering": ["requested_on", "id"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="approval",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="supply_chain.awardapproval",
            ),
        ),
    ]
