# Generated by Django 6.0.8 on 2026-09-23 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0009_award_approvals"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="covers_shortfall_of",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shortfall_covered_by",
                to="supply_chain.contract",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="stock_class",
            field=models.CharField(
                choices=[("consumable", "consumable"), ("durable", "durable")], default="consumable", max_length=16
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="confirmed_by_payee_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
