# Generated by Django 6.0.8 on 2026-09-23 22:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0024_workflowschedule_interval_hours"),
        ("supply_chain", "0010_payment_confirmation_shortfall_durable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("program_id", models.IntegerField(db_index=True)),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                ("check_kinds", models.JSONField(blank=True, default=list)),
                ("movement_kinds", models.JSONField(blank=True, default=list)),
                ("recipient_email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "cadence",
                    models.CharField(
                        choices=[("immediate", "immediate"), ("daily_digest", "daily digest")],
                        default="immediate",
                        max_length=16,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("movements_seen_through", models.BigIntegerField(default=0)),
                ("last_digest_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "commodity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_subscriptions",
                        to="supply_chain.commodity",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_alert_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supply_point",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_subscriptions",
                        to="supply_chain.supplypoint",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertNotice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("program_id", models.IntegerField(db_index=True)),
                ("kind", models.CharField(choices=[("check", "check"), ("movement", "movement")], max_length=16)),
                ("subject_kind", models.CharField(max_length=64)),
                ("subject", models.JSONField(blank=True, default=dict)),
                ("facts", models.JSONField(blank=True, default=dict)),
                ("since", models.DateField(blank=True, null=True)),
                ("record_url", models.CharField(blank=True, default="", max_length=512)),
                ("detected_at", models.DateTimeField(db_index=True)),
                (
                    "delivery",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("queued", "queued"),
                            ("email_disabled", "email disabled"),
                            ("no_address", "no address"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("sent_to", models.CharField(blank=True, default="", max_length=254)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notices",
                        to="supply_chain.alertsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AlertCheckState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("check_key", models.CharField(max_length=255)),
                ("first_reported_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_states",
                        to="supply_chain.alertsubscription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UpdateLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("program_id", models.IntegerField(db_index=True)),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("token_hint", models.CharField(blank=True, default="", max_length=8)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contracts",
                    models.ManyToManyField(blank=True, related_name="update_links", to="supply_chain.contract"),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supply_update_links",
                        to="labs.labsorg",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supply_points",
                    models.ManyToManyField(blank=True, related_name="update_links", to="supply_chain.supplypoint"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UpdateLinkSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=32)),
                ("operation", models.CharField(max_length=64)),
                ("result_type", models.CharField(blank=True, default="", max_length=32)),
                ("result_id", models.IntegerField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="supply_chain.updatelink",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="alertsubscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("recipient_user__isnull", False), ("recipient_email", "")),
                    models.Q(("recipient_user__isnull", True), models.Q(("recipient_email", ""), _negated=True)),
                    _connector="OR",
                ),
                name="alert_subscription_has_one_recipient",
            ),
        ),
        migrations.AddIndex(
            model_name="alertnotice",
            index=models.Index(fields=["subscription", "delivery"], name="supply_chai_subscri_1f490e_idx"),
        ),
        migrations.AddIndex(
            model_name="alertcheckstate",
            index=models.Index(fields=["subscription", "cleared_at"], name="supply_chai_subscri_6629cd_idx"),
        ),
        migrations.AddConstraint(
            model_name="alertcheckstate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cleared_at__isnull", True)),
                fields=("subscription", "check_key"),
                name="alert_one_open_state_per_check",
            ),
        ),
    ]
