# Generated by Django 6.0.8 on 2026-09-24 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0012_seed_alert_beat_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="payment_terms",
            field=models.CharField(
                choices=[("on_delivery", "on delivery"), ("advance", "advance")], default="on_delivery", max_length=16
            ),
        ),
    ]
