# Generated by Django 6.0.8 on 2026-09-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0013_contract_payment_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="awardapproval",
            name="decision_note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
