# Generated by Django 6.0.8 on 2026-09-24 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0014_link_submission_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="awardapproval",
            name="rests_on_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approvals_resting_on",
                to="supply_chain.document",
            ),
        ),
    ]
