# Generated by Django 6.0.8 on 2026-09-24 04:33

import django.db.models.deletion
from django.db import migrations, models


def carry_contracts(apps, schema_editor):
    """Name the order each existing submission touched, so the order page --
    which now asks the database for them -- still lists the ones made before.

    `summary` is left empty on these: what they reported at the time was never
    kept, and describe() falls back to reading the row as it is now.
    """
    Submission = apps.get_model("supply_chain", "UpdateLinkSubmission")
    Receipt = apps.get_model("supply_chain", "Receipt")
    Payment = apps.get_model("supply_chain", "Payment")
    Shipment = apps.get_model("supply_chain", "Shipment")
    Contract = apps.get_model("supply_chain", "Contract")
    lookups = {
        "contract_update": lambda rid: Contract.objects.filter(pk=rid).values_list("pk", flat=True).first(),
        "receipt_record": lambda rid: Receipt.objects.filter(pk=rid).values_list("contract_id", flat=True).first(),
        "payment_confirm": lambda rid: Payment.objects.filter(pk=rid)
        .values_list("invoice__contract_id", flat=True)
        .first(),
        "shipment_record": lambda rid: Shipment.objects.filter(pk=rid).values_list("contract_id", flat=True).first(),
        "shipment_update": lambda rid: Shipment.objects.filter(pk=rid).values_list("contract_id", flat=True).first(),
    }
    for submission in Submission.objects.filter(operation__in=list(lookups), result_id__isnull=False):
        contract_id = lookups[submission.operation](submission.result_id)
        if contract_id:
            Submission.objects.filter(pk=submission.pk).update(contract_id=contract_id)


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0014_approval_decision_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="updatelinksubmission",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="link_submissions",
                to="supply_chain.contract",
            ),
        ),
        migrations.AddField(
            model_name="updatelinksubmission",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(carry_contracts, migrations.RunPython.noop, hints={"run_on_secondary": False}),
    ]
