# Generated by Django 6.0.8 on 2026-09-24 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0024_workflowschedule_interval_hours"),
        ("supply_chain", "0017_item_components_per"),
    ]

    operations = [
        migrations.AddField(
            model_name="awardapproval",
            name="decision_recorded_by_org",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="labs.labsorg"
            ),
        ),
        migrations.AddField(
            model_name="awardapproval",
            name="decision_source",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="updatelink",
            name="approvals",
            field=models.ManyToManyField(blank=True, related_name="update_links", to="supply_chain.awardapproval"),
        ),
    ]
