# Generated by Django 6.0.8 on 2026-09-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0019_update_link_coverage"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertsubscription",
            name="recipient_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="updatelinksubmission",
            name="happened_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
