# Generated by Django 6.0.8 on 2026-09-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0020_link_update_dates_and_alert_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=300)),
                ("program_ids", models.JSONField(default=list)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
