# Generated by Django 6.0.8 on 2026-09-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0021_portfolio"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplypoint",
            name="location_label",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="supplypoint",
            name="location_precision",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="supplypoint",
            name="location_source",
            field=models.CharField(
                blank=True,
                choices=[("recorded", "recorded"), ("org_hq", "org hq"), ("parent", "parent"), ("country", "country")],
                default="",
                max_length=16,
            ),
        ),
    ]
