# Generated by Django 6.0.8 on 2026-09-25 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0025_supplier_is_a_company"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="entered_by",
            field=models.CharField(db_default="program", 
                choices=[("program", "program"), ("supplier", "supplier")], default="program", max_length=16
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="entered_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="round",
            name="visibility",
            field=models.CharField(db_default="public", 
                choices=[("public", "public"), ("private", "private")], default="public", max_length=16
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="origin",
            field=models.CharField(db_default="program", 
                choices=[("program", "program"), ("self_registered", "self registered")],
                default="program",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="reviewed_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SupplierOffering",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("therapeutic_food", "Therapeutic food (treats severe malnutrition)"),
                            ("supplementary_food", "Supplementary food (treats moderate)"),
                            ("oral_rehydration", "Oral rehydration"),
                            ("micronutrient", "Micronutrient"),
                            ("antibiotic", "Antibiotic"),
                            ("antimalarial", "Antimalarial"),
                            ("anthelmintic", "Anthelmintic"),
                            ("diagnostic", "Diagnostic"),
                            ("equipment", "Equipment"),
                            ("consumable", "Consumable"),
                        ],
                        max_length=32,
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("unicef_material_number", models.CharField(blank=True, default="", max_length=32)),
                ("gtin", models.CharField(blank=True, default="", max_length=14)),
                ("pack_description", models.CharField(blank=True, default="", max_length=255)),
                ("base_per_pack", models.IntegerField(blank=True, null=True)),
                ("typical_lead_time_days", models.IntegerField(blank=True, null=True)),
                ("minimum_order", models.CharField(blank=True, default="", max_length=128)),
                ("countries_served", models.JSONField(blank=True, default=list)),
                ("certifications", models.JSONField(blank=True, default=list)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offerings",
                        to="supply_chain.supplierprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "product_name"],
            },
        ),
    ]
