# Generated by Django 6.0.8 on 2026-09-25 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0024_workflowschedule_interval_hours"),
        ("supply_chain", "0026_supplier_market"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("we_recorded", "we recorded"),
                            ("partner_reported", "partner reported"),
                            ("supplier_reported", "supplier reported"),
                            ("commcare_form", "commcare form"),
                            ("connect_visit", "connect visit"),
                            ("document", "document"),
                        ],
                        max_length=32,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("program_id", models.IntegerField(db_index=True)),
                ("opportunity_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("batch", models.CharField(blank=True, default="", max_length=64)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("quantity_unit", models.CharField(max_length=32)),
                ("reference", models.CharField(blank=True, default="", max_length=64)),
                ("carrier", models.CharField(blank=True, default="", max_length=255)),
                ("dispatched_on", models.DateField(db_index=True)),
                ("expected_on", models.DateField(blank=True, null=True)),
                ("received_on", models.DateField(blank=True, null=True)),
                ("quantity_received", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("dispatched", "dispatched"), ("received", "received")],
                        db_index=True,
                        default="dispatched",
                        max_length=16,
                    ),
                ),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consignments",
                        to="supply_chain.commodity",
                    ),
                ),
                (
                    "dispatch_movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consignment_dispatched",
                        to="supply_chain.movement",
                    ),
                ),
                (
                    "from_supply_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consignments_out",
                        to="supply_chain.supplypoint",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="supply_chain.item",
                    ),
                ),
                (
                    "receipt_movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consignment_received",
                        to="supply_chain.movement",
                    ),
                ),
                (
                    "recorded_by_org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="labs.labsorg",
                    ),
                ),
                (
                    "to_supply_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consignments_in",
                        to="supply_chain.supplypoint",
                    ),
                ),
                (
                    "via_supply_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consignments_via",
                        to="supply_chain.supplypoint",
                    ),
                ),
            ],
            options={
                "ordering": ["-dispatched_on", "-id"],
            },
        ),
    ]
