# Generated by Django 6.0.8 on 2026-09-25 21:53

from django.db import migrations, models


def carry_delivery_point(apps, schema_editor):
    """Each tender's one delivery point becomes a one-place list, keyed `main`.

    The requested Incoterm, which lived inside the old point, moves to its own
    field. A tender with no point keeps an empty list: it could not open
    before, and still cannot until it names a place or accepts collection.
    """
    Tender = apps.get_model("supply_chain", "Tender")
    for tender in Tender.objects.all():
        point = dict(tender.delivery_point or {})
        incoterm = point.pop("incoterm_requested", "") or ""
        point = {k: v for k, v in point.items() if v}
        tender.delivery_points = [{"key": "main", **point}] if point else []
        tender.incoterm_requested = incoterm
        tender.save(update_fields=["delivery_points", "incoterm_requested"])


def restore_delivery_point(apps, schema_editor):
    Tender = apps.get_model("supply_chain", "Tender")
    for tender in Tender.objects.all():
        first = dict((tender.delivery_points or [{}])[0])
        first.pop("key", None)
        if tender.incoterm_requested:
            first["incoterm_requested"] = tender.incoterm_requested
        tender.delivery_point = first
        tender.save(update_fields=["delivery_point"])


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0027_round_is_a_tender"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="buyer_transport_amount",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="delivery_mode",
            field=models.CharField(
                choices=[("delivered", "delivered"), ("pickup", "pickup")],
                db_default="delivered",
                default="delivered",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="delivery_point_keys",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="quote",
            name="pickup_location",
            field=models.CharField(blank=True, db_default="", default="", max_length=255),
        ),
        migrations.AddField(
            model_name="tender",
            name="delivery_points",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="tender",
            name="incoterm_requested",
            field=models.CharField(blank=True, db_default="", default="", max_length=16),
        ),
        migrations.AddField(
            model_name="tender",
            name="pickup_accepted",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.RunPython(carry_delivery_point, restore_delivery_point, hints={"run_on_secondary": False}),
    ]
