# Generated by Django 6.0.8 on 2026-09-25 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0024_workflowschedule_interval_hours"),
        ("supply_chain", "0030_consignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="brief",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
        migrations.AddField(
            model_name="tender",
            name="hue",
            field=models.CharField(blank=True, db_default="", default="", max_length=7),
        ),
        migrations.AddField(
            model_name="tender",
            name="invited_orgs",
            field=models.ManyToManyField(blank=True, related_name="tenders_invited_to", to="labs.labsorg"),
        ),
        migrations.AddField(
            model_name="tender",
            name="owner_org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenders_published",
                to="labs.labsorg",
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="slug",
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
