# Generated by Django 6.0.8 on 2026-09-26 15:35

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("supply_chain", "0031_tender_listing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationCall",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("program_id", models.IntegerField(db_index=True, null=True)),
                ("operation", models.CharField(max_length=64)),
                ("actor_is_agent", models.BooleanField(default=False)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("web", "web"),
                            ("mcp", "mcp"),
                            ("api", "api"),
                            ("command", "command"),
                            ("supplier", "supplier"),
                        ],
                        max_length=16,
                    ),
                ),
                ("acting_org_id", models.IntegerField(blank=True, null=True)),
                ("source_ref", models.CharField(blank=True, default="", max_length=512)),
                ("source_excerpt", models.TextField(blank=True, default="")),
                ("payload_digest", models.CharField(blank=True, default="", max_length=64)),
                ("result", models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ("recorded_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Revision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("program_id", models.IntegerField(db_index=True, null=True)),
                ("object_id", models.CharField(max_length=64)),
                (
                    "action",
                    models.CharField(
                        choices=[("create", "create"), ("update", "update"), ("delete", "delete")], max_length=8
                    ),
                ),
                ("changes", models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "call",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="supply_chain.operationcall",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="contenttypes.contenttype"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="operationcall",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_ref", ""), _negated=True),
                fields=("program_id", "operation", "source_ref", "payload_digest"),
                name="supply_opcall_idempotent_source",
            ),
        ),
        migrations.AddIndex(
            model_name="revision",
            index=models.Index(
                fields=["content_type", "object_id", "recorded_at"], name="supply_chai_content_0948b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="revision",
            index=models.Index(fields=["program_id", "recorded_at"], name="supply_chai_program_bffeb8_idx"),
        ),
    ]
