# Generated by Django 6.0.8 on 2026-09-28 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0024_workflowschedule_interval_hours"),
        ("supply_chain", "0034_operationcall_replays"),
    ]

    operations = [
        migrations.AddField(
            model_name="movement",
            name="estimated",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="movement",
            name="reverses",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reversal",
                to="supply_chain.movement",
            ),
        ),
        migrations.AddField(
            model_name="movement",
            name="visit_id",
            field=models.CharField(blank=True, db_default="", db_index=True, default="", max_length=64),
        ),
        migrations.AddConstraint(
            model_name="movement",
            constraint=models.UniqueConstraint(
                condition=models.Q(models.Q(("visit_id", ""), _negated=True), ("reverses__isnull", True)),
                fields=("program_id", "visit_id", "item"),
                name="movement_one_consumption_per_visit_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="movement",
            constraint=models.UniqueConstraint(
                condition=models.Q(models.Q(("visit_id", ""), _negated=True), ("reverses__isnull", False)),
                fields=("program_id", "visit_id", "item"),
                name="movement_one_reversal_per_visit_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="movement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reverses__isnull", True),
                    models.Q(
                        ("from_supply_point__isnull", True),
                        ("kind", "consumption"),
                        ("to_supply_point__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="movement_reversal_is_consumption_back_in",
            ),
        ),
    ]
