# Generated by Django 6.0.8 on 2026-09-28 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0035_movement_from_visits"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispensingRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("program_id", models.IntegerField(db_index=True)),
                ("opportunity_id", models.IntegerField(db_index=True)),
                ("lines", models.JSONField(default=list)),
                ("forms", models.JSONField(blank=True, default=list)),
                ("reports", models.JSONField(blank=True, default=dict)),
                ("active_from", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("inactive", "inactive")], default="active", max_length=16
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispensing_rules",
                        to="supply_chain.item",
                    ),
                ),
                (
                    "resupply_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dispensing_rules",
                        to="supply_chain.supplypoint",
                    ),
                ),
            ],
            options={
                "ordering": ["opportunity_id", "item_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("program_id", "opportunity_id", "item"), name="uniq_dispensing_rule_opp_item"
                    )
                ],
            },
        ),
    ]
