# Generated by Django 6.0.8 on 2026-09-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0036_dispensing_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplypoint",
            name="connect_user_uuid",
            field=models.CharField(blank=True, db_default="", db_index=True, default="", max_length=64),
        ),
    ]
