# Generated by Django 6.0.8 on 2026-09-29 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0037_supply_point_connect_user_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerVisit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("program_id", models.IntegerField(db_index=True)),
                ("opportunity_id", models.IntegerField(db_index=True)),
                ("visit_id", models.CharField(max_length=64)),
                ("xform_id", models.CharField(blank=True, default="", max_length=64)),
                ("connect_username", models.CharField(blank=True, default="", max_length=150)),
                ("visit_date", models.DateField(db_index=True)),
                ("status", models.CharField(blank=True, default="", max_length=32)),
                ("form_name", models.CharField(blank=True, default="", max_length=255)),
                ("outcomes", models.JSONField(blank=True, default=dict)),
                ("answers", models.JSONField(blank=True, default=dict)),
                (
                    "supply_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="visits",
                        to="supply_chain.supplypoint",
                    ),
                ),
            ],
            options={
                "ordering": ["-visit_date", "-id"],
                "indexes": [
                    models.Index(fields=["supply_point", "visit_date"], name="supply_chai_supply__5f77dc_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("program_id", "visit_id"), name="uniq_worker_visit_program_visit")
                ],
            },
        ),
    ]
