# Generated by Django 6.0.8 on 2026-09-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0039_seed_visit_consumption_beat_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockcount",
            name="kind",
            field=models.CharField(
                choices=[
                    ("self_reported", "self reported"),
                    ("physical_count", "physical count"),
                    ("override", "override"),
                    ("reported_receipt", "reported receipt"),
                ],
                max_length=16,
            ),
        ),
    ]
