# Generated by Django 6.0.8 on 2026-10-02 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0025_userocstoken'),
        ('supply_chain', '0040_stock_count_reported_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='freight_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='operationcall',
            name='source_sender',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='outreach',
            name='responded_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='supply_chain.contract'),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_terms',
            field=models.CharField(blank=True, db_default='', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quote',
            name='supplier_reference',
            field=models.CharField(blank=True, db_default='', default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='charge',
            name='source',
            field=models.CharField(choices=[('we_recorded', 'we recorded'), ('partner_reported', 'partner reported'), ('supplier_reported', 'supplier reported'), ('forwarder_reported', 'forwarder reported'), ('commcare_form', 'commcare form'), ('connect_visit', 'connect visit'), ('document', 'document')], max_length=32),
        ),
        migrations.AlterField(
            model_name='consignment',
            name='source',
            field=models.CharField(choices=[('we_recorded', 'we recorded'), ('partner_reported', 'partner reported'), ('supplier_reported', 'supplier reported'), ('forwarder_reported', 'forwarder reported'), ('commcare_form', 'commcare form'), ('connect_visit', 'connect visit'), ('document', 'document')], max_length=32),
        ),
        migrations.AlterField(
            model_name='contract',
            name='source',
            field=models.CharField(choices=[('we_recorded', 'we recorded'), ('partner_reported', 'partner reported'), ('supplier_reported', 'supplier reported'), ('forwarder_reported', 'forwarder reported'), ('commcare_form', 'commcare form'), ('connect_visit', 'connect visit'), ('document', 'document')], max_length=32),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='source',
            field=models.CharField(choices=[('we_recorded', 'we recorded'), ('partner_reported', 'partner reported'), ('supplier_reported', 'supplier reported'), ('forwarder_reported', 'forwarder reported'), ('commcare_form', 'commcare form'), ('connect_visit', 'connect visit'), ('document', 'document')], max_length=32),
        ),
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.CharField(choices=[('we_recorded', 'we recorded'), ('partner_reported', 'partner reported'), ('supplier_reported', 'supplier reported'), ('forwarder_reported', 'forwarder reported'), ('commcare_form', 'commcare form'), ('connect_visit', 'connect visit'), ('document', 'document')], max_length=32),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='source',
            field=models.CharField(choices=[('we_recorded', 'we recorded'), ('partner_reported', 'partner reported'), ('supplier_reported', 'supplier reported'), ('forwarder_reported', 'forwarder reported'), ('commcare_form', 'commcare form'), ('connect_visit', 'connect visit'), ('document', 'document')], max_length=32),
        ),
        migrations.AlterField(
            model_name='movement',
            name='source',
            field=models.CharField(choices=[('we_recorded', 'we recorded'), ('partner_reported', 'partner reported'), ('supplier_reported', 'supplier reported'), ('forwarder_reported', 'forwarder reported'), ('commcare_form', 'commcare form'), ('connect_visit', 'connect visit'), ('document', 'document')], max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='supply_chain.invoice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='source',
            field=models.CharField(choices=[('we_recorded', 'we recorded'), ('partner_reported', 'partner reported'), ('supplier_reported', 'supplier reported'), ('forwarder_reported', 'forwarder reported'), ('commcare_form', 'commcare form'), ('connect_visit', 'connect visit'), ('document', 'document')], max_length=32),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='source',
            field=models.CharField(choices=[('we_recorded', 'we recorded'), ('partner_reported', 'partner reported'), ('supplier_reported', 'supplier reported'), ('forwarder_reported', 'forwarder reported'), ('commcare_form', 'commcare form'), ('connect_visit', 'connect visit'), ('document', 'document')], max_length=32),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='source',
            field=models.CharField(choices=[('we_recorded', 'we recorded'), ('partner_reported', 'partner reported'), ('supplier_reported', 'supplier reported'), ('forwarder_reported', 'forwarder reported'), ('commcare_form', 'commcare form'), ('connect_visit', 'connect visit'), ('document', 'document')], max_length=32),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='source',
            field=models.CharField(choices=[('we_recorded', 'we recorded'), ('partner_reported', 'partner reported'), ('supplier_reported', 'supplier reported'), ('forwarder_reported', 'forwarder reported'), ('commcare_form', 'commcare form'), ('connect_visit', 'connect visit'), ('document', 'document')], max_length=32),
        ),
        migrations.AlterField(
            model_name='supplypoint',
            name='source',
            field=models.CharField(choices=[('we_recorded', 'we recorded'), ('partner_reported', 'partner reported'), ('supplier_reported', 'supplier reported'), ('forwarder_reported', 'forwarder reported'), ('commcare_form', 'commcare form'), ('connect_visit', 'connect visit'), ('document', 'document')], max_length=32),
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('we_recorded', 'we recorded'), ('partner_reported', 'partner reported'), ('supplier_reported', 'supplier reported'), ('forwarder_reported', 'forwarder reported'), ('commcare_form', 'commcare form'), ('connect_visit', 'connect visit'), ('document', 'document')], max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('program_id', models.IntegerField(db_index=True)),
                ('kind', models.CharField(choices=[('question', 'question'), ('promise', 'promise')], max_length=16)),
                ('text', models.TextField()),
                ('raised_on', models.DateField()),
                ('due_on', models.DateField(blank=True, null=True)),
                ('resolved_on', models.DateField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, default='')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='supply_chain.contract')),
                ('owed_to_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_commitments', to='labs.labsorg')),
                ('recorded_by_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='labs.labsorg')),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='supply_chain.tender')),
            ],
            options={
                'ordering': ['raised_on', 'pk'],
            },
        ),
    ]
