# Generated by Django 6.0.8 on 2026-10-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0043_payment_contract_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="commitment",
            name="reply_sent_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tender",
            name="duty_estimate_percent",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name="tender",
            name="duty_terms",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", ""),
                    ("buyer_waiver", "buyer waiver"),
                    ("buyer_pays", "buyer pays"),
                    ("supplier_ddp", "supplier ddp"),
                ],
                db_default="",
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="duty_terms_set_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
