# Generated by Django 6.0.8 on 2026-10-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0044_tender_duty_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="clearing_estimate_per_unit",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name="tender",
            name="freight_estimate_per_unit",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name="tender",
            name="import_estimates_set_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
