# Generated by Django 6.0.8 on 2026-10-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0045_tender_import_estimates"),
    ]

    operations = [
        migrations.AddField(
            model_name="award",
            name="open_at_decision",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
