# Generated by Django 6.0.8 on 2026-10-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0047_seed_clone_top_up_beat_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationcall",
            name="source_sent_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
