# Generated by Django 6.0.8 on 2026-10-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0049_document_validity"),
    ]

    operations = [
        migrations.AddField(
            model_name="workervisit",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workervisit",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supplypoint",
            name="location_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("recorded", "recorded"),
                    ("visits", "visits"),
                    ("org_hq", "org hq"),
                    ("parent", "parent"),
                    ("served", "served"),
                    ("country", "country"),
                ],
                db_default="",
                default="",
                max_length=16,
            ),
        ),
    ]
