# Generated by Django 6.0.8 on 2026-10-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0050_worker_visit_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplyWorkflowView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("program_id", models.IntegerField(db_index=True)),
                ("slug", models.SlugField(max_length=80)),
                ("label", models.CharField(max_length=80)),
                ("workflow_definition_id", models.IntegerField()),
                ("opportunity_id", models.IntegerField(blank=True, null=True)),
                ("replaces", models.CharField(blank=True, default="", max_length=80)),
                ("position", models.IntegerField(default=0)),
                ("created_by", models.CharField(blank=True, default="", max_length=150)),
            ],
            options={
                "ordering": ["program_id", "position", "id"],
                "constraints": [
                    models.UniqueConstraint(fields=("program_id", "slug"), name="uniq_supply_workflow_view_slug")
                ],
            },
        ),
    ]
