# Generated by Django 6.0.8 on 2026-10-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supply_chain", "0051_supply_workflow_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispensingrule",
            name="cases",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="workervisit",
            name="entity_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="workervisit",
            name="form_xmlns",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
