# Generated by Django 5.2.12 on 2026-09-16 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("labs", "0023_labsorg"),
        ("solicitations", "0010_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Solicitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, default="")),
                ("scope_of_work", models.TextField(blank=True, default="")),
                (
                    "solicitation_type",
                    models.CharField(
                        choices=[("eoi", "Expression of Interest"), ("rfp", "Request for Proposal")],
                        default="eoi",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("active", "Active"), ("closed", "Closed")],
                        default="closed",
                        max_length=16,
                    ),
                ),
                ("application_deadline", models.DateField(blank=True, null=True)),
                ("expected_start_date", models.DateField(blank=True, null=True)),
                ("expected_end_date", models.DateField(blank=True, null=True)),
                ("estimated_scale", models.CharField(blank=True, default="", max_length=200)),
                ("contact_email", models.EmailField(blank=True, default="", max_length=320)),
                ("questions", models.JSONField(blank=True, default=list)),
                ("evaluation_criteria", models.JSONField(blank=True, default=list)),
                ("published_on", models.DateField(blank=True, null=True)),
                ("decision_on", models.DateField(blank=True, null=True)),
                ("target_countries", models.CharField(blank=True, default="", max_length=500)),
                ("announcement_url", models.CharField(blank=True, default="", max_length=1000)),
                ("form_url", models.CharField(blank=True, default="", max_length=1000)),
                ("response_spreadsheet_id", models.CharField(blank=True, default="", max_length=120)),
                ("response_tab", models.CharField(blank=True, default="", max_length=120)),
                ("column_map", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "sa_access_state",
                    models.CharField(
                        choices=[
                            ("unknown", "not checked"),
                            ("ok", "readable"),
                            ("denied", "no access"),
                            ("missing", "no response sheet recorded"),
                        ],
                        default="unknown",
                        max_length=12,
                    ),
                ),
                ("sa_access_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_ingested_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-published_on", "title"],
            },
        ),
        migrations.CreateModel(
            name="SolicitationResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("llo_entity_name", models.CharField(blank=True, default="", max_length=300)),
                ("org_name", models.CharField(blank=True, default="", max_length=300)),
                ("responses", models.JSONField(blank=True, default=dict)),
                ("submitted_by_name", models.CharField(blank=True, default="", max_length=200)),
                ("submitted_by_email", models.CharField(blank=True, default="", max_length=500)),
                ("submission_date", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="submitted", max_length=16)),
                ("source_row", models.IntegerField()),
                ("source_url", models.CharField(blank=True, default="", max_length=1000)),
                ("country_as_submitted", models.CharField(blank=True, default="", max_length=300)),
                ("website_as_submitted", models.CharField(blank=True, default="", max_length=500)),
                (
                    "match_state",
                    models.CharField(
                        choices=[
                            ("unmatched", "not matched"),
                            ("email", "matched on a contact email"),
                            ("name", "matched on organisation name"),
                            ("human", "attributed by a person"),
                        ],
                        default="unmatched",
                        max_length=12,
                    ),
                ),
                ("match_basis", models.TextField(blank=True, default="")),
                ("imported_at", models.DateTimeField(auto_now=True)),
                (
                    "llo_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitation_responses",
                        to="labs.labsorg",
                    ),
                ),
                (
                    "solicitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="solicitations.solicitation",
                    ),
                ),
            ],
            options={
                "ordering": ["-submission_date", "source_row"],
                "indexes": [models.Index(fields=["match_state"], name="solicitatio_match_s_36c0c8_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("solicitation", "source_row"), name="uniq_response_per_source_row")
                ],
            },
        ),
    ]
