# Generated by Django 5.2.12 on 2026-09-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solicitations", "0011_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitationresponse",
            name="match_state",
            field=models.CharField(
                choices=[
                    ("unmatched", "not matched"),
                    ("email", "matched on a contact email"),
                    ("name", "matched on organisation name"),
                    ("human", "attributed by a person"),
                    ("not_an_llo", "not an organisation — dismissed by a person"),
                ],
                default="unmatched",
                max_length=12,
            ),
        ),
    ]
