# Generated by Django 5.2.12 on 2026-09-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solicitations", "0012_alter_solicitationresponse_match_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitation",
            name="delivery_type",
            field=models.CharField(blank=True, default="", max_length=48),
        ),
    ]
