# Generated by Django 5.2.12 on 2026-06-19 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0002_campaign_workspace_donor_householdstat_region_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("worker_id", models.CharField(max_length=16)),
                ("first", models.CharField(max_length=64)),
                ("last", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("gender", models.CharField(max_length=1)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("region_id", models.CharField(max_length=64)),
                ("lga", models.CharField(max_length=128)),
                ("role_id", models.CharField(max_length=64)),
                ("rate", models.IntegerField(default=0)),
                ("days_worked", models.IntegerField(default=0)),
                ("days_approved", models.IntegerField(default=0)),
                ("amount", models.IntegerField(default=0)),
                ("kyc", models.CharField(max_length=16)),
                ("pay", models.CharField(max_length=16)),
                ("bank", models.CharField(blank=True, max_length=64)),
                ("acct", models.CharField(blank=True, max_length=32)),
                ("nin", models.CharField(blank=True, max_length=32)),
                ("passport", models.CharField(blank=True, max_length=32, null=True)),
                ("enrolled", models.CharField(blank=True, max_length=32)),
                ("attendance", models.IntegerField(default=0)),
                ("prior_campaigns", models.IntegerField(default=0)),
                ("duplicate", models.BooleanField(default=False)),
                ("dup_with", models.CharField(blank=True, max_length=16, null=True)),
                ("fraud_rules", models.JSONField(default=list)),
                ("linked", models.JSONField(default=list)),
                ("investigation", models.JSONField(blank=True, null=True)),
                ("documents", models.JSONField(default=list)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="workers", to="campaign.campaign"
                    ),
                ),
            ],
            options={
                "db_table": "campaign_worker",
            },
        ),
    ]
