# Generated by Django 5.2.12 on 2026-06-19 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0004_activity_microplan"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.CharField(max_length=8)),
                ("enrolled", models.BigIntegerField(default=0)),
                ("attended", models.BigIntegerField(default=0)),
                ("paid", models.BigIntegerField(default=0)),
                ("order", models.IntegerField(default=0)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="report_days", to="campaign.campaign"
                    ),
                ),
            ],
            options={
                "db_table": "campaign_report_day",
                "ordering": ["order"],
            },
        ),
    ]
