# Generated by Django 5.2.12 on 2026-06-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0007_workercase"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyntheticCommCareDomain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("domain", models.CharField(db_index=True, max_length=128, unique=True)),
                ("label", models.CharField(blank=True, max_length=200)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "campaign_synthetic_commcare_domain",
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="commcare_domain",
            field=models.CharField(blank=True, db_index=True, default="", max_length=128),
        ),
    ]
