# Generated by Django 5.2.12 on 2026-07-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_trail", "0002_auditevent_query_string_alter_auditevent_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="request_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
