# Generated by Django 5.2.12 on 2026-07-28 14:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_trail', '0003_alter_auditevent_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='occurred_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
