# Generated by Django 5.2.12 on 2026-08-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriorAuditVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_id', models.IntegerField(db_index=True)),
                ('session_id', models.IntegerField(db_index=True)),
                ('session_title', models.CharField(blank=True, default='', max_length=255)),
                ('visit_id', models.CharField(max_length=64)),
                ('blob_id', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=32)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['opportunity_id', 'visit_id', 'blob_id', '-completed_at'], name='idx_prior_audit_lookup')],
                'constraints': [models.UniqueConstraint(fields=('session_id', 'visit_id', 'blob_id'), name='uniq_prior_audit_session_visit_blob')],
            },
        ),
    ]
