# Generated by Django 5.2.12 on 2026-08-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_priorauditverdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='priorauditprojectionstate',
            name='watermark',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
