# Generated by Django 5.2.17 on 2026-09-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0005_priorauditprojectionstate_watermark"),
    ]

    operations = [
        migrations.AddField(
            model_name="priorauditverdict",
            name="username",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="priorauditverdict",
            name="visit_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="priorauditverdict",
            index=models.Index(fields=["opportunity_id", "username"], name="idx_prior_audit_flw"),
        ),
    ]
