# Generated by Django 4.2.5 on 2026-01-01 07:52

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0004_program_currency_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="program_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="programapplication",
            name="program_application_id",
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
