# Generated by Django 5.2.12 on 2026-04-19 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mcp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tool_name", models.CharField(db_index=True, max_length=100)),
                ("is_write", models.BooleanField(default=False)),
                ("arguments", models.JSONField(blank=True, default=dict)),
                ("success", models.BooleanField()),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("version_before", models.IntegerField(blank=True, null=True)),
                ("version_after", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcp_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mcp_audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="mcp_audit_l_user_id_7874dd_idx"),
                    models.Index(fields=["tool_name", "-created_at"], name="mcp_audit_l_tool_na_7b7505_idx"),
                ],
            },
        ),
    ]
