# Generated by Django 6.0.8 on 2026-09-27 20:01

"""The delegated-grant tables now live in the canopy SDK (app ``canopy_host``).

Nothing is copied across on purpose: a ``DelegatedAccessToken`` lives at most 15
minutes and a used ``jti`` only until the statement it belongs to has expired,
so the worst a deploy costs is canopy redeeming one fresh grant — which it does
the next time the visitor's panel mints.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0004_delegated_grant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delegatedaccesstoken",
            name="user",
        ),
        migrations.DeleteModel(
            name="SeenJTI",
        ),
        migrations.DeleteModel(
            name="DelegatedAccessToken",
        ),
    ]
