# Generated by Django 6.0.8 on 2026-10-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0008_mcpaccesstoken_scope_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcpaccesstoken",
            name="scope",
            field=models.CharField(
                choices=[
                    ("full", "Full access"),
                    ("no-uservisit-data", "No user visit data"),
                    ("coach-images", "Coaching pictures only"),
                ],
                default="full",
                help_text="What the token may reach. See connect_labs/mcp/token_scopes.py.",
                max_length=20,
            ),
        ),
    ]
