# Generated by Django 6.0.8 on 2026-10-09 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScopeConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("organization", "organization"),
                            ("program", "program"),
                            ("opportunity", "opportunity"),
                            ("user", "user"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scope_key", models.CharField(max_length=200)),
                ("namespace", models.CharField(max_length=60)),
                ("data", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=0)),
                ("updated_by", models.CharField(blank=True, default="", max_length=150)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("scope_type", "scope_key", "namespace"), name="uniq_scope_config")
                ],
            },
        ),
        migrations.CreateModel(
            name="ScopeConfigChange",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.PositiveIntegerField()),
                ("before", models.JSONField(default=dict)),
                ("after", models.JSONField(default=dict)),
                ("changed_by", models.CharField(blank=True, default="", max_length=150)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("via", models.CharField(blank=True, default="", max_length=80)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="scope_config.scopeconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
