# Generated by Django 5.2.12 on 2026-07-31 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulse", "0002_pulsegridcell_pulsework"),
    ]

    operations = [
        migrations.CreateModel(
            name="PulseProgram",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("program_id", models.IntegerField(db_index=True, unique=True)),
                ("name", models.CharField(blank=True, max_length=300)),
                ("delivery_type", models.CharField(blank=True, db_index=True, max_length=48)),
                ("org_slug", models.CharField(blank=True, max_length=120)),
                ("currency", models.CharField(blank=True, max_length=8)),
                ("is_test", models.BooleanField(db_index=True, default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
