# Generated by Django 5.2.12 on 2026-07-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulse", "0003_pulseprogram"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pulsegridcell",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="pulsegridcell",
            name="program_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="pulsegridcell",
            unique_together={("lat_q", "lon_q", "service_slug", "program_id")},
        ),
    ]
