# Generated by Django 5.2.12 on 2026-07-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulse", "0004_alter_pulsegridcell_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PulseOrganization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.CharField(db_index=True, max_length=120, unique=True)),
                ("name", models.CharField(blank=True, max_length=300)),
                ("funder_slug", models.CharField(blank=True, max_length=120)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
