# Generated by Django 5.2.12 on 2026-07-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulse", "0005_pulseorganization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pulseevent",
            name="org_slug",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="pulsework",
            name="org_slug",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
