# Generated by Django 5.2.12 on 2026-08-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulse", "0006_alter_pulseevent_org_slug_alter_pulsework_org_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pulseevent",
            name="worker_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="pulsework",
            name="worker_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
