# Generated by Django 5.2.12 on 2026-08-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulse", "0007_alter_pulseevent_worker_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pulseevent",
            name="service_slug",
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
        migrations.AlterField(
            model_name="pulsegridcell",
            name="service_slug",
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
        migrations.AlterField(
            model_name="pulseopportunity",
            name="service_slug",
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
        migrations.AlterField(
            model_name="pulsework",
            name="service_slug",
            field=models.CharField(blank=True, db_index=True, max_length=48),
        ),
    ]
