# Generated by Django 5.2.12 on 2026-08-13 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulse", "0008_alter_pulseevent_service_slug_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PulseReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.CharField(db_index=True, max_length=64, unique=True)),
                ("eyebrow", models.CharField(blank=True, default="Donor stewardship report", max_length=120)),
                ("title", models.CharField(blank=True, max_length=300)),
                ("prepared_for", models.CharField(blank=True, max_length=300)),
                ("gift_line", models.CharField(blank=True, max_length=300)),
                ("window_start", models.DateField(blank=True, null=True)),
                ("window_end", models.DateField(blank=True, null=True)),
                ("program_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("org_slug", models.CharField(blank=True, max_length=120)),
                ("opportunity_id", models.IntegerField(blank=True, null=True)),
                ("service_slug", models.CharField(blank=True, max_length=48)),
                ("intro", models.TextField(blank=True)),
                ("where_we_worked", models.TextField(blank=True)),
                ("partner_funding", models.TextField(blank=True)),
                ("footnote", models.TextField(blank=True)),
                ("photo", models.ImageField(blank=True, null=True, upload_to="pulse_reports/")),
                ("photo_caption", models.TextField(blank=True)),
                ("deliverables", models.JSONField(blank=True, default=list)),
                ("site_chips", models.JSONField(blank=True, default=list)),
                ("show_partner_names", models.BooleanField(default=True)),
                ("revoked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pulse_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
