# Generated by Django 5.2.12 on 2026-08-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulse", "0009_pulsereport"),
    ]

    operations = [
        migrations.AddField(
            model_name="pulseevent",
            name="folded_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
