# Generated by Django 5.2.12 on 2026-08-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulse", "0010_pulseevent_folded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="pulsecursor",
            name="backfill_complete_to",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
