# Generated by Django 5.2.12 on 2026-08-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0011_pulsecursor_backfill_complete_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulsecursor',
            name='last_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
