# Generated by Django 5.2.12 on 2026-09-06 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulse", "0012_pulsecursor_last_failed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="PulsePartner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=300, unique=True)),
                ("short", models.CharField(blank=True, max_length=120)),
                ("imported_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PulsePartnerAlias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.CharField(max_length=120, unique=True)),
                ("why", models.TextField()),
                ("imported_at", models.DateTimeField(auto_now=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="aliases", to="pulse.pulsepartner"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "pulse partner aliases",
                "ordering": ["slug"],
            },
        ),
    ]
