# Generated by Django 5.2.12 on 2026-09-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulse", "0013_partner_directory"),
    ]

    operations = [
        migrations.AddField(
            model_name="pulsepartner",
            name="country_iso3",
            field=models.CharField(blank=True, db_index=True, max_length=3),
        ),
        migrations.AddField(
            model_name="pulsepartner",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pulsepartner",
            name="location_label",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="pulsepartner",
            name="location_precision",
            field=models.CharField(
                blank=True, choices=[("city", "city"), ("region", "region"), ("country", "country")], max_length=8
            ),
        ),
        migrations.AddField(
            model_name="pulsepartner",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
