# Generated by Django 5.2.12 on 2026-09-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulse", "0014_partner_hq_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="pulsepartner",
            name="joined_at",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="pulsepartner",
            name="joined_basis",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
