# Generated by Django 5.2.12 on 2026-09-16 15:41

from django.db import migrations


class Migration(migrations.Migration):
    # The carry MUST run first: it reads these tables to populate the
    # registry, and every join date on the network growth curve is a
    # directory fact Connect has never held and cannot regenerate.
    dependencies = [
        ("marketplace", "0002_carry_pulse_partners"),
        ("pulse", "0015_partner_joined_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pulsepartneralias",
            name="partner",
        ),
        migrations.DeleteModel(
            name="PulsePartner",
        ),
        migrations.DeleteModel(
            name="PulsePartnerAlias",
        ),
    ]
