# Generated by Django 6.0.8 on 2026-09-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulse", "0017_pulseopportunity_budget_per_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pulseopportunity",
            name="usd_rate",
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=18, null=True),
        ),
    ]
