# Generated by Django 6.0.8 on 2026-09-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulse", "0018_pulseopportunity_usd_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="pulseopportunity",
            name="is_test",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
