# Generated by Django 6.0.8 on 2026-09-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulse", "0019_pulseopportunity_is_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="PulseCostEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("opportunity_id", models.IntegerField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed cost (start-up, equipment, other)"),
                            ("org_fee", "Organisation's per-service fee paid outside Connect"),
                        ],
                        max_length=16,
                    ),
                ),
                ("usd", models.DecimalField(decimal_places=2, max_digits=16)),
                ("date", models.DateField(blank=True, null=True)),
                ("reason", models.TextField()),
                (
                    "source",
                    models.CharField(
                        blank=True, help_text="Where the figure came from: contract, ledger, email.", max_length=300
                    ),
                ),
                ("entered_by", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "pulse cost entries",
            },
        ),
        migrations.AddField(
            model_name="pulseopportunity",
            name="invoices_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PulseInvoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("opportunity_id", models.IntegerField(db_index=True)),
                ("invoice_number", models.CharField(max_length=50)),
                ("amount", models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ("amount_usd", models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("service_delivery", models.BooleanField(default=True)),
                ("exchange_rate_id", models.IntegerField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("opportunity_id", "invoice_number")},
            },
        ),
        migrations.CreateModel(
            name="PulseInvoiceReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("opportunity_id", models.IntegerField(db_index=True)),
                ("invoice_number", models.CharField(max_length=50)),
                ("usd_override", models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                (
                    "exclude",
                    models.BooleanField(default=False, help_text="Leave this invoice out of every cost figure."),
                ),
                ("reason", models.TextField()),
                ("decided_by", models.CharField(blank=True, max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("opportunity_id", "invoice_number")},
            },
        ),
    ]
