# Generated by Django 6.0.8 on 2026-09-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulse", "0020_invoices_and_cost_entries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pulsecostentry",
            name="kind",
            field=models.CharField(
                choices=[
                    ("fixed", "Startup and supplies"),
                    ("org_fee", "Organisation's per-service fee paid outside Connect"),
                ],
                max_length=16,
            ),
        ),
    ]
