# Generated by Django 6.0.8 on 2026-09-20 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulse", "0021_startup_and_supplies_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="PulseOppGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=300)),
                ("org_slug", models.CharField(blank=True, max_length=120)),
                ("why", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "grouped opportunity",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="pulseopportunity",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="pulse.pulseoppgroup",
            ),
        ),
    ]
