# Generated by Django 6.0.8 on 2026-09-20 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pulse", "0022_pulseoppgroup_pulseopportunity_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="pulsecostentry",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_entries",
                to="pulse.pulseoppgroup",
            ),
        ),
        migrations.AlterField(
            model_name="pulsecostentry",
            name="opportunity_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
