"""Regenerate connect_labs/pulse/data/hq_towns.tsv.gz, the head-office gazetteer.

    curl -O https://download.geonames.org/export/dump/cities500.zip && unzip cities500.zip
    curl -O https://download.geonames.org/export/dump/countryInfo.txt
    python tools/build_hq_towns.py cities500.txt countryInfo.txt

Why a separate file from ``static/pulse/towns.js``: that one is shipped to the
browser for Pulse's "nearest town" labels and is cut to the countries Connect
delivers in, so it has to stay small. The directory lists organisations far
outside that set -- Zambia, Malawi, Ethiopia, a London office -- and every one
of them silently fell to "country only" because their towns were simply not in
the table. This file is server-side only, so it can afford the whole continent.

Scope: every African country, plus the non-African countries the LLO Directory
actually names. Add a code to EXTRA when the directory grows a new one; the
import's findings tab reports any organisation it could not place.

Gzipped TSV (about 700 KB), read once per process. Columns: asciiname, alpha2,
lat, lon, population. Sorted by country, then by population descending, so the
resolver can rank matches by size.
"""

from __future__ import annotations

import gzip
import sys
from pathlib import Path

EXTRA = {
    # South / South-East Asia and the Middle East partners named in the directory.
    "IN",
    "BD",
    "PK",
    "AF",
    "NP",
    "ID",
    "PH",
    "MY",
    "IR",
    "TR",
    # Head offices abroad, and the rest of the directory's non-African rows.
    "GB",
    "UA",
    "HT",
}

OUT = Path(__file__).resolve().parent.parent / "connect_labs" / "pulse" / "data" / "hq_towns.tsv.gz"


def main(cities_path: str, country_info_path: str) -> None:
    africa = set()
    for line in Path(country_info_path).read_text(encoding="utf-8").splitlines():
        if line.startswith("#") or not line.strip():
            continue
        cols = line.split("\t")
        if cols[8] == "AF":
            africa.add(cols[0])
    keep = africa | EXTRA

    rows = []
    with open(cities_path, encoding="utf-8") as fh:
        for line in fh:
            cols = line.rstrip("\n").split("\t")
            cc = cols[8]
            if cc not in keep:
                continue
            name = cols[2].strip()
            if not name:
                continue
            rows.append((cc, -int(cols[14] or 0), name, round(float(cols[4]), 3), round(float(cols[5]), 3)))
    rows.sort()

    header = (
        "# GeoNames cities500 (c) GeoNames, CC BY 4.0 -- geonames.org. "
        "Generated by tools/build_hq_towns.py; do not hand-edit.\n"
    )
    body = "".join(f"{name}\t{cc}\t{lat}\t{lon}\t{-negpop}\n" for cc, negpop, name, lat, lon in rows)
    # Gzipped with a fixed mtime so a regeneration from the same input is
    # byte-identical and does not show up as a diff.
    OUT.write_bytes(gzip.compress((header + body).encode("utf-8"), mtime=0))
    print(f"wrote {len(rows)} towns across {len({r[0] for r in rows})} countries to {OUT}")


if __name__ == "__main__":
    main(*sys.argv[1:3])
