# Generated by Django 5.2.12 on 2026-08-26 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("admin_boundaries", "0003_adminboundary_extra_adminboundary_parent_boundary_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("dhs", "DHS Program"),
                            ("igme", "UN IGME (via UNICEF SDMX)"),
                            ("worldpop", "WorldPop"),
                            ("hapi", "HDX HAPI"),
                            ("derived", "Derived"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "indicator",
                    models.CharField(blank=True, help_text="Blank when a loader writes several", max_length=40),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("rows_written", models.IntegerField(default=0)),
                ("countries", models.IntegerField(default=0)),
                ("ok", models.BooleanField(default=False)),
                ("detail", models.TextField(blank=True, help_text="Errors, skips, and notes worth keeping")),
            ],
            options={
                "db_table": "labs_indicator_ingest_run",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="IndicatorValue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "indicator",
                    models.CharField(db_index=True, help_text="Measure code — see measures.MEASURES", max_length=40),
                ),
                ("iso_code", models.CharField(db_index=True, max_length=3)),
                ("admin_level", models.PositiveSmallIntegerField(db_index=True)),
                ("year", models.IntegerField(db_index=True, help_text="Reference year of the estimate")),
                ("value", models.FloatField()),
                (
                    "ci_low",
                    models.FloatField(
                        blank=True, help_text="Lower bound of the published uncertainty interval", null=True
                    ),
                ),
                (
                    "ci_high",
                    models.FloatField(
                        blank=True, help_text="Upper bound of the published uncertainty interval", null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("dhs", "DHS Program"),
                            ("igme", "UN IGME (via UNICEF SDMX)"),
                            ("worldpop", "WorldPop"),
                            ("hapi", "HDX HAPI"),
                            ("derived", "Derived"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        blank=True,
                        help_text="Specific origin — survey code, dataset release, or API dataset name",
                        max_length=200,
                    ),
                ),
                (
                    "license_code",
                    models.CharField(
                        choices=[
                            ("cc-by-4.0", "CC BY 4.0"),
                            ("cc-by-3.0-igo", "CC BY 3.0 IGO"),
                            ("cc-by-nc-sa-3.0-igo", "CC BY-NC-SA 3.0 IGO"),
                            ("open-api", "Open API, no explicit licence"),
                            ("derived", "Derived (inherits from inputs)"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "method",
                    models.TextField(
                        blank=True,
                        help_text="For derived values, the formula and inputs used. Shown verbatim in the methodology panel.",
                    ),
                ),
                ("retrieved_at", models.DateTimeField(help_text="When this value was fetched from its source")),
                (
                    "extra",
                    models.JSONField(blank=True, default=dict, help_text="Source-specific metadata kept verbatim"),
                ),
                (
                    "boundary",
                    models.ForeignKey(
                        help_text="The administrative unit this value describes",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicator_values",
                        to="admin_boundaries.adminboundary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicator value",
                "verbose_name_plural": "Indicator values",
                "db_table": "labs_indicator_value",
                "ordering": ["iso_code", "admin_level", "indicator", "-year"],
                "indexes": [
                    models.Index(fields=["indicator", "iso_code", "year"], name="labs_indica_indicat_dad112_idx"),
                    models.Index(fields=["indicator", "admin_level", "year"], name="labs_indica_indicat_696c19_idx"),
                    models.Index(fields=["boundary", "indicator"], name="labs_indica_boundar_4f87d2_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("indicator", "boundary", "year", "source"), name="labs_indicator_value_uniq"
                    )
                ],
            },
        ),
    ]
