# Generated by Django 5.2.12 on 2026-08-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0002_alter_indicatorvalue_source_alter_ingestrun_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicatorvalue",
            name="source_url",
            field=models.URLField(
                blank=True, help_text="Where a reader can go to see this figure at its source", max_length=500
            ),
        ),
    ]
