# Generated by Django 5.2.12 on 2026-08-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indicators", "0003_indicatorvalue_source_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatorvalue",
            name="source",
            field=models.CharField(
                choices=[
                    ("dhs", "DHS Program"),
                    ("igme", "UN IGME (via UNICEF SDMX)"),
                    ("worldpop", "WorldPop"),
                    ("hapi", "HDX HAPI"),
                    ("worldbank", "World Bank (WDI)"),
                    ("dhs_calibrated", "DHS, re-levelled to current national trend"),
                    ("derived", "Derived"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ingestrun",
            name="source",
            field=models.CharField(
                choices=[
                    ("dhs", "DHS Program"),
                    ("igme", "UN IGME (via UNICEF SDMX)"),
                    ("worldpop", "WorldPop"),
                    ("hapi", "HDX HAPI"),
                    ("worldbank", "World Bank (WDI)"),
                    ("dhs_calibrated", "DHS, re-levelled to current national trend"),
                    ("derived", "Derived"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
