# Generated by Django 5.2.12 on 2026-08-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0007_source_url_db_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatorvalue",
            name="license_code",
            field=models.CharField(
                choices=[
                    ("cc-by-4.0", "CC BY 4.0"),
                    ("cc-by-3.0-igo", "CC BY 3.0 IGO"),
                    ("cc-by-3.0", "CC BY 3.0 Unported"),
                    ("cc-by-nc-sa-3.0-igo", "CC BY-NC-SA 3.0 IGO"),
                    ("open-api", "Open API, no explicit licence"),
                    ("derived", "Derived (inherits from inputs)"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="indicatorvalue",
            name="source",
            field=models.CharField(
                choices=[
                    ("dhs", "DHS Program"),
                    ("igme", "UN IGME (via UNICEF SDMX)"),
                    ("worldpop", "WorldPop"),
                    ("hapi", "HDX HAPI"),
                    ("worldbank", "World Bank (WDI)"),
                    ("igme_subnational", "UN IGME (subnational model)"),
                    ("dhs_calibrated", "DHS (re-levelled)"),
                    ("map", "Malaria Atlas Project"),
                    ("derived", "Derived"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ingestrun",
            name="source",
            field=models.CharField(
                choices=[
                    ("dhs", "DHS Program"),
                    ("igme", "UN IGME (via UNICEF SDMX)"),
                    ("worldpop", "WorldPop"),
                    ("hapi", "HDX HAPI"),
                    ("worldbank", "World Bank (WDI)"),
                    ("igme_subnational", "UN IGME (subnational model)"),
                    ("dhs_calibrated", "DHS (re-levelled)"),
                    ("map", "Malaria Atlas Project"),
                    ("derived", "Derived"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ResearchNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "indicator",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Measure code this is about; blank for research that spans indicators",
                        max_length=40,
                    ),
                ),
                ("topic", models.SlugField(help_text="Short slug — what question this note answers", max_length=80)),
                ("summary", models.CharField(help_text="The conclusion, in one line", max_length=300)),
                (
                    "body",
                    models.TextField(
                        help_text="The reasoning, in markdown. What was tried, what was found, what it means."
                    ),
                ),
                (
                    "checks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Falsifiable claims, re-run every time the note is read. See research.revalidate.",
                    ),
                ),
                (
                    "alternatives",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Sources considered: name, url, licence, verdict, and why it was or was not adopted",
                    ),
                ),
                (
                    "scanned_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When a FULL alternative-source scan was last run for this indicator",
                        null=True,
                    ),
                ),
                ("author", models.CharField(blank=True, help_text="Who or what wrote this", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Research note",
                "db_table": "labs_indicator_research",
                "ordering": ["indicator", "topic"],
                "constraints": [
                    models.UniqueConstraint(fields=("indicator", "topic"), name="labs_indicator_research_uniq")
                ],
            },
        ),
    ]
