# Generated by Django 5.2.12 on 2026-08-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0008_research_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatorvalue",
            name="source",
            field=models.CharField(
                choices=[
                    ("dhs", "DHS Program"),
                    ("igme", "UN IGME (via UNICEF SDMX)"),
                    ("worldpop", "WorldPop"),
                    ("worldpop_raster", "WorldPop (1km grid, UN-adjusted)"),
                    ("hapi", "HDX HAPI"),
                    ("worldbank", "World Bank (WDI)"),
                    ("igme_subnational", "UN IGME (subnational model)"),
                    ("dhs_calibrated", "DHS (re-levelled)"),
                    ("map", "Malaria Atlas Project"),
                    ("derived", "Derived"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ingestrun",
            name="source",
            field=models.CharField(
                choices=[
                    ("dhs", "DHS Program"),
                    ("igme", "UN IGME (via UNICEF SDMX)"),
                    ("worldpop", "WorldPop"),
                    ("worldpop_raster", "WorldPop (1km grid, UN-adjusted)"),
                    ("hapi", "HDX HAPI"),
                    ("worldbank", "World Bank (WDI)"),
                    ("igme_subnational", "UN IGME (subnational model)"),
                    ("dhs_calibrated", "DHS (re-levelled)"),
                    ("map", "Malaria Atlas Project"),
                    ("derived", "Derived"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
