# Generated by Django 5.2.12 on 2026-09-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0011_alter_indicatorvalue_source_alter_ingestrun_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indicatorvalue",
            name="license_code",
            field=models.CharField(
                choices=[
                    ("cc-by-4.0", "CC BY 4.0"),
                    ("cc-by-3.0-igo", "CC BY 3.0 IGO"),
                    ("cc-by-3.0", "CC BY 3.0 Unported"),
                    ("cc-by-nc-sa-3.0-igo", "CC BY-NC-SA 3.0 IGO"),
                    ("open-api", "Open API, no explicit licence"),
                    ("public-domain", "Public domain"),
                    ("derived", "Derived (inherits from inputs)"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="indicatorvalue",
            name="source",
            field=models.CharField(
                choices=[
                    ("dhs", "DHS Program"),
                    ("igme", "UN IGME (via UNICEF SDMX)"),
                    ("worldpop", "WorldPop"),
                    ("worldpop_raster", "WorldPop (1km grid, UN-adjusted)"),
                    ("hapi", "HDX HAPI"),
                    ("worldbank", "World Bank (WDI)"),
                    ("igme_subnational", "UN IGME (subnational model)"),
                    ("dhs_calibrated", "DHS (re-levelled)"),
                    ("map", "Malaria Atlas Project"),
                    ("map_worldpop", "MAP accessibility x WorldPop"),
                    ("ghsl", "GHS-SMOD (DEGURBA) x WorldPop"),
                    ("unicef_sdmx", "UNICEF (subnational SDMX)"),
                    ("chirps", "CHIRPS x WorldPop"),
                    ("derived", "Derived"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ingestrun",
            name="source",
            field=models.CharField(
                choices=[
                    ("dhs", "DHS Program"),
                    ("igme", "UN IGME (via UNICEF SDMX)"),
                    ("worldpop", "WorldPop"),
                    ("worldpop_raster", "WorldPop (1km grid, UN-adjusted)"),
                    ("hapi", "HDX HAPI"),
                    ("worldbank", "World Bank (WDI)"),
                    ("igme_subnational", "UN IGME (subnational model)"),
                    ("dhs_calibrated", "DHS (re-levelled)"),
                    ("map", "Malaria Atlas Project"),
                    ("map_worldpop", "MAP accessibility x WorldPop"),
                    ("ghsl", "GHS-SMOD (DEGURBA) x WorldPop"),
                    ("unicef_sdmx", "UNICEF (subnational SDMX)"),
                    ("chirps", "CHIRPS x WorldPop"),
                    ("derived", "Derived"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
