# Generated by Django 6.0.8 on 2026-10-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indicators", "0013_lbw_sources"),
    ]

    operations = [
        migrations.CreateModel(
            name="PmcModelRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("inputs_hash", models.CharField(max_length=64, unique=True)),
                ("request", models.JSONField(help_text="The exact request sent to the worker")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("result", models.JSONField(blank=True, help_text="The worker's result document", null=True)),
                ("error", models.TextField(blank=True)),
                (
                    "timings",
                    models.JSONField(
                        blank=True, default=dict, help_text="Seconds spent booting, waiting and simulating"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Last claim or save; judges a stuck 'running' row"),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "labs_pmc_model_run",
                "ordering": ["-created_at"],
            },
        ),
    ]
