# Generated by Django 5.2.12 on 2026-06-19 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=64)),
                ("round", models.CharField(blank=True, max_length=64)),
                ("country", models.CharField(default="Nigeria", max_length=128)),
                ("period", models.CharField(blank=True, max_length=128)),
                ("status", models.CharField(default="Active", max_length=32)),
                ("days_elapsed", models.IntegerField(default=0)),
                ("days_total", models.IntegerField(default=0)),
                ("target_pop", models.BigIntegerField(default=0)),
            ],
            options={
                "db_table": "campaign_campaign",
            },
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("country", models.CharField(default="Nigeria", max_length=128)),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "db_table": "campaign_workspace",
            },
        ),
        migrations.CreateModel(
            name="Donor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("donor_id", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("short", models.CharField(max_length=64)),
                ("committed", models.BigIntegerField(default=0)),
                ("color", models.CharField(default="#5D70D2", max_length=16)),
                ("order", models.IntegerField(default=0)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="donors", to="campaign.campaign"
                    ),
                ),
            ],
            options={
                "db_table": "campaign_donor",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HouseholdStat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("registered", models.BigIntegerField(default=0)),
                ("visited", models.BigIntegerField(default=0)),
                ("members", models.BigIntegerField(default=0)),
                ("members_reached", models.BigIntegerField(default=0)),
                ("coverage", models.JSONField(default=list)),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="household_stat",
                        to="campaign.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_household_stat",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("region_id", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("lgas", models.JSONField(default=list)),
                ("order", models.IntegerField(default=0)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="regions", to="campaign.campaign"
                    ),
                ),
            ],
            options={
                "db_table": "campaign_region",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="RegionPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("planned_wf", models.IntegerField(default=0)),
                ("actual_wf", models.IntegerField(default=0)),
                ("budget", models.BigIntegerField(default=0)),
                ("spent", models.BigIntegerField(default=0)),
                ("target", models.BigIntegerField(default=0)),
                ("reached", models.BigIntegerField(default=0)),
                ("vaccine_alloc", models.BigIntegerField(default=0)),
                ("vaccine_used", models.BigIntegerField(default=0)),
                (
                    "region",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="plan", to="campaign.region"
                    ),
                ),
            ],
            options={
                "db_table": "campaign_region_plan",
            },
        ),
        migrations.CreateModel(
            name="WorkerRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role_id", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("rate", models.IntegerField(default=0)),
                ("order", models.IntegerField(default=0)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_roles",
                        to="campaign.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_worker_role",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="campaigns", to="campaign.workspace"
            ),
        ),
    ]
