# Generated by Django 5.2.12 on 2026-06-19 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0003_worker"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activity_id", models.CharField(max_length=16)),
                ("name", models.CharField(max_length=255)),
                ("donor", models.CharField(max_length=64)),
                ("status", models.CharField(default="Planned", max_length=16)),
                ("start", models.CharField(blank=True, max_length=32)),
                ("end", models.CharField(blank=True, max_length=32)),
                ("requests", models.IntegerField(default=0)),
                ("workers", models.IntegerField(default=0)),
                ("region", models.CharField(max_length=128)),
                ("target", models.BigIntegerField(default=0)),
                ("reached", models.BigIntegerField(default=0)),
                ("synced", models.BooleanField(default=False)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="campaign.campaign"
                    ),
                ),
            ],
            options={
                "db_table": "campaign_activity",
            },
        ),
        migrations.CreateModel(
            name="Microplan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("microplan_id", models.CharField(max_length=16)),
                ("region_id", models.CharField(max_length=64)),
                ("region", models.CharField(max_length=128)),
                ("lga", models.CharField(max_length=128)),
                ("settlements", models.IntegerField(default=0)),
                ("wards", models.IntegerField(default=0)),
                ("planned_wf", models.IntegerField(default=0)),
                ("actual_wf", models.IntegerField(default=0)),
                ("roles", models.JSONField(default=list)),
                ("budget", models.BigIntegerField(default=0)),
                ("spent", models.BigIntegerField(default=0)),
                ("planned_to_date", models.BigIntegerField(default=0)),
                ("target", models.BigIntegerField(default=0)),
                ("objective", models.BigIntegerField(default=0)),
                ("goal_pct", models.IntegerField(default=95)),
                ("reached", models.BigIntegerField(default=0)),
                ("doses", models.BigIntegerField(default=0)),
                ("doses_used", models.BigIntegerField(default=0)),
                ("cold_boxes", models.IntegerField(default=0)),
                ("vehicles", models.IntegerField(default=0)),
                ("status", models.CharField(default="Planned", max_length=16)),
                ("owner", models.CharField(blank=True, max_length=128)),
                ("updated", models.CharField(blank=True, max_length=32)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="microplans", to="campaign.campaign"
                    ),
                ),
            ],
            options={
                "db_table": "campaign_microplan",
            },
        ),
    ]
