# Generated by Django 5.2.12 on 2026-06-19 17:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0005_reportday"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("at", models.DateTimeField(default=django.utils.timezone.now)),
                ("user", models.CharField(max_length=255)),
                ("action", models.TextField()),
                ("module", models.CharField(max_length=64)),
                ("ip", models.CharField(blank=True, default="", max_length=64)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="campaign.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_audit_log",
                "ordering": ["-at", "-id"],
            },
        ),
    ]
