# Generated by Django 5.2.12 on 2026-06-19 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaign", "0006_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerCase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("case_id", models.CharField(db_index=True, help_text="CommCare case id", max_length=64)),
                ("case_type", models.CharField(default="campaign_worker", max_length=64)),
                (
                    "worker_id",
                    models.CharField(db_index=True, help_text="W##### external id (a case property)", max_length=16),
                ),
                (
                    "region_id",
                    models.CharField(db_index=True, help_text="AdminBoundary state boundary_id", max_length=100),
                ),
                ("lga", models.CharField(blank=True, db_index=True, max_length=128)),
                ("ward", models.CharField(blank=True, max_length=128)),
                ("properties", models.JSONField(default=dict)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_cases",
                        to="campaign.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_worker_case",
                "indexes": [models.Index(fields=["campaign", "region_id"], name="campaign_wo_campaig_4c6f96_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("campaign", "case_id"), name="campaign_worker_case_uniq")
                ],
            },
        ),
    ]
