# Generated by Django 5.2.12 on 2026-04-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0009_userconnecttoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComputedEntityCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("opportunity_id", models.IntegerField(db_index=True)),
                ("config_hash", models.CharField(db_index=True, help_text="Hash of analysis config", max_length=32)),
                ("visit_count", models.IntegerField(help_text="Visit count when cached, for invalidation")),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("entity_id", models.CharField(db_index=True, max_length=255)),
                ("entity_name", models.CharField(blank=True, max_length=500)),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Representative FLW (typically first(username) per entity)",
                        max_length=255,
                    ),
                ),
                ("aggregated_fields", models.JSONField(default=dict, help_text="Aggregated field values")),
                ("total_visits", models.IntegerField(default=0)),
                ("first_visit_date", models.DateField(blank=True, null=True)),
                ("last_visit_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "labs_computed_entity_cache",
                "indexes": [
                    models.Index(
                        fields=["opportunity_id", "config_hash", "visit_count"], name="labs_comput_opportu_a8fd34_idx"
                    ),
                    models.Index(
                        fields=["opportunity_id", "config_hash", "username"], name="labs_comput_opportu_68cc93_idx"
                    ),
                ],
            },
        ),
    ]
