# Generated by Django 5.2.12 on 2026-07-08 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0014_deletedworkflowbackup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("definition_id", models.IntegerField()),
                ("definition_name", models.CharField(blank=True, max_length=255)),
                ("opportunity_id", models.IntegerField(blank=True, null=True)),
                ("program_id", models.IntegerField(blank=True, null=True)),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekdays", "Weekdays (Mon–Fri)"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=16,
                    ),
                ),
                ("hour", models.PositiveSmallIntegerField(default=6)),
                ("day_of_week", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("day_of_month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("enabled", models.BooleanField(default=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ok", "OK"),
                            ("failed", "Failed"),
                            ("auth_expired", "Auth expired"),
                            ("running", "Running"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "labs_workflow_schedule",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("definition_id", "opportunity_id", "program_id", "owner"),
                        name="uniq_schedule_per_definition_scope_owner",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
    ]
