# Generated by Django 5.2.12 on 2026-07-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0017_usercchqtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawvisitcache",
            name="user_id",
            field=models.CharField(
                blank=True, help_text="Connect user UUID, for building shareable visit links", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="rawvisitcache",
            name="user_visit_id",
            field=models.CharField(
                blank=True, help_text="Connect UserVisit UUID, for building shareable visit links", max_length=64
            ),
        ),
    ]
