# Generated by Django 5.2.17 on 2026-09-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0020_workflowschedule_biweekly_cadence"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="computedentitycache",
            name="uniq_computed_entity_cache_opp_config_entity",
        ),
        migrations.RemoveConstraint(
            model_name="computedflwcache",
            name="uniq_computed_flw_cache_opp_config_username",
        ),
        migrations.RemoveConstraint(
            model_name="computedvisitcache",
            name="uniq_computed_visit_cache_opp_config_visit",
        ),
        migrations.RemoveIndex(
            model_name="computedentitycache",
            name="labs_comput_opportu_a8fd34_idx",
        ),
        migrations.RemoveIndex(
            model_name="computedentitycache",
            name="labs_comput_opportu_68cc93_idx",
        ),
        migrations.RemoveIndex(
            model_name="computedflwcache",
            name="labs_comput_opportu_4919d4_idx",
        ),
        migrations.RemoveIndex(
            model_name="computedvisitcache",
            name="labs_comput_opportu_ef588d_idx",
        ),
        migrations.AddField(
            model_name="computedentitycache",
            name="pipeline_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="computedflwcache",
            name="pipeline_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="computedvisitcache",
            name="pipeline_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="computedentitycache",
            index=models.Index(
                fields=["opportunity_id", "pipeline_id", "config_hash", "visit_count"],
                name="labs_comput_opportu_1eb162_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="computedentitycache",
            index=models.Index(
                fields=["opportunity_id", "pipeline_id", "config_hash", "username"],
                name="labs_comput_opportu_00495b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="computedflwcache",
            index=models.Index(
                fields=["opportunity_id", "pipeline_id", "config_hash", "visit_count"],
                name="labs_comput_opportu_a23bfb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="computedvisitcache",
            index=models.Index(
                fields=["opportunity_id", "pipeline_id", "config_hash", "visit_count"],
                name="labs_comput_opportu_6d2499_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="computedentitycache",
            constraint=models.UniqueConstraint(
                fields=("opportunity_id", "pipeline_id", "config_hash", "entity_id"),
                name="uniq_computed_entity_cache_opp_pipe_config_entity",
            ),
        ),
        migrations.AddConstraint(
            model_name="computedflwcache",
            constraint=models.UniqueConstraint(
                fields=("opportunity_id", "pipeline_id", "config_hash", "username"),
                name="uniq_computed_flw_cache_opp_pipe_config_username",
            ),
        ),
        migrations.AddConstraint(
            model_name="computedvisitcache",
            constraint=models.UniqueConstraint(
                fields=("opportunity_id", "pipeline_id", "config_hash", "visit_id"),
                name="uniq_computed_visit_cache_opp_pipe_config_visit",
            ),
        ),
    ]
