# Generated by Django 5.2.12 on 2026-09-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0021_computed_cache_pipeline_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowschedule',
            name='interval_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowschedule',
            name='cadence',
            field=models.CharField(choices=[('daily', 'Daily'), ('interval', 'Every N hours'), ('weekdays', 'Weekdays (Mon–Fri)'), ('weekly', 'Weekly'), ('biweekly', 'Every 2 weeks'), ('monthly', 'Monthly')], max_length=16),
        ),
    ]
