# Generated by Django 5.2.12 on 2026-09-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0021_computed_cache_pipeline_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawvisitcache',
            name='images_fetched',
            field=models.BooleanField(default=False),
        ),
    ]
