# Generated by Django 5.2.12 on 2026-09-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0022_rawvisitcache_images_fetched"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabsOrg",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("name", models.CharField(max_length=300)),
                ("short_name", models.CharField(blank=True, default="", max_length=120)),
                ("country", models.CharField(blank=True, default="", max_length=2)),
                ("connect_organization_id", models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ("connect_organization_slug", models.CharField(blank=True, db_index=True, default="", max_length=200)),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "labs organisation",
                "ordering": ["name"],
            },
        ),
    ]
