# Generated by Django 5.2.12 on 2026-07-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labs", "0013_rawvisitcache_pipeline_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedWorkflowBackup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("definition_id", models.IntegerField(db_index=True)),
                ("opportunity_id", models.IntegerField(db_index=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("template_type", models.CharField(blank=True, default="", max_length=100)),
                ("definition_data", models.JSONField(default=dict)),
                ("render_code", models.TextField(blank=True, default="")),
                ("deleted_by", models.CharField(blank=True, default="", max_length=150)),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Deleted workflow backup",
                "verbose_name_plural": "Deleted workflow backups",
                "db_table": "labs_deleted_workflow_backup",
                "ordering": ["-id"],
            },
        ),
    ]
