# Generated by Django 5.2.12 on 2026-05-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microplans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="footprintbuilding",
            name="geom_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
